# Version mapping for Z_RELEASE_VERSION files across release branches
# This file is maintained in the main branch and used by the update-release-versions workflow
# to automatically update Z_RELEASE_VERSION files in each release branch

release_mappings:
  release-2.11: "2.11.9"
  release-2.12: "2.12.5"  
  release-2.13: "2.13.4"
  release-2.14: "2.14.1"
  release-2.15: "2.15.0"
  # Add new release mappings here as needed
  # release-2.16: "2.16.0"