apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/volsync-addon-controller?rev=4298b79e1fe3b7f2df4e731c169cd6979996481f
    build.appstudio.redhat.com/commit_sha: 4298b79e1fe3b7f2df4e731c169cd6979996481f
    build.appstudio.redhat.com/target_branch: release-2.16
    pac.test.appstudio.openshift.io/branch: release-2.16
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54803309997"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-cerygg
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/volsync-addon-controller-acm-216-on-push-ghpl9
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.16"
    pac.test.appstudio.openshift.io/original-prname: volsync-addon-controller-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "1147"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/volsync-addon-controller
    pac.test.appstudio.openshift.io/repository: volsync-addon-controller-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 4298b79e1fe3b7f2df4e731c169cd6979996481f
    pac.test.appstudio.openshift.io/sha-title: 'fix(deps): update module sigs.k8s.io/controller-runtime
      to v0.22.4 (#1147)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/volsync-addon-controller/commit/4298b79e1fe3b7f2df4e731c169cd6979996481f
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.16
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/volsync-addon-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: volsync-addon-controller
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'grafana-dashboard-loader-acm-216,
      kube-rbac-proxy-acm-216, observatorium-operator-acm-216, prometheus-acm-216,
      config-policy-controller-acm-216, endpoint-monitoring-operator-acm-216, metrics-collector-acm-216,
      node-exporter-acm-216, multicluster-role-assignment-acm-216, prometheus-alertmanager-acm-216,
      rbac-query-proxy-acm-216, kube-state-metrics-acm-216, observatorium-acm-216,
      multicluster-operators-channel-acm-216, must-gather-acm-216, multicloud-integrations-acm-216,
      multicluster-observability-addon-acm-216, multicluster-observability-operator-acm-216,
      multicluster-operators-application-acm-216, acm-cli-acm-216, cert-policy-controller-acm-216,
      governance-policy-propagator-acm-216, multicluster-operators-subscription-acm-216,
      prometheus-config-reloader-acm-216, thanos-receive-controller-acm-216, governance-policy-addon-controller-acm-216,
      grafana-acm-216, submariner-addon-acm-216, cluster-permission-acm-216, governance-policy-framework-addon-acm-216,
      memcached-exporter-acm-216, prometheus-operator-acm-216, thanos-acm-216' is(are)
      not included in snapshot due to missing valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-216-release-acm-216-lz2bg":{"lastUpdateTime":"2025-11-07T14:25:42.337875972Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762524879"
    test.appstudio.openshift.io/pr-group: refs/heads/release-2.16
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/volsync-addon-controller
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-216","status":"TestPassed","lastUpdateTime":"2025-11-07T14:25:42.337875972Z","details":"Integration
      test passed","startTime":"2025-11-07T14:25:06.656772626Z","completionTime":"2025-11-07T14:25:42.337875972Z","testPipelineRunName":"enterprise-contract-acm-216-g6tv4"}]'
  creationTimestamp: "2025-11-07T14:25:06Z"
  generateName: release-acm-216-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-216
    appstudio.openshift.io/build-pipelinerun: volsync-addon-controller-acm-216-on-push-ghpl9
    appstudio.openshift.io/component: volsync-addon-controller-acm-216
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54803309997"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: volsync-addon-controller-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "1147"
    pac.test.appstudio.openshift.io/repository: volsync-addon-controller-acm-210
    pac.test.appstudio.openshift.io/sha: 4298b79e1fe3b7f2df4e731c169cd6979996481f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: volsync-addon-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762525498"
    test.appstudio.openshift.io/pr-group-sha: 3541f3343890e1de964805d2179832e232906962277c9e4d68dd003c503ed1
    test.appstudio.openshift.io/type: component
  name: release-acm-216-lz2bg
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-216
    uid: 36e17c1d-3fe4-44ec-96e0-7fac572eda72
  resourceVersion: "5748200749"
  uid: fff85d34-c0da-4aa2-9151-587c0dc9ee36
spec:
  application: release-acm-216
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-216@sha256:2b6f1e57833aa98d7e0acec558b1da44138b1eed22185bb4459d41463f1cb193
    name: insights-client-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c5a46b852fdcf8d875379289637fa1d93fabb844
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-216@sha256:3f8b4784bcdd6a05757c94a8a5b402e441cfda04b9613bcf4ff2482a0f851a83
    name: mtv-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: c7bfbe48b4e0de377b69c6fefdfd5a40f4615c23
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-216@sha256:f256d41485714938211c7759323210aa59d78e61a3f65c29a1d160f6d4bfdca5
    name: multiclusterhub-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: defb69aca02b5d168b91f98aebda355b7446ff1f
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-216@sha256:32d16c2e6bdc7cd146c5d492c703ce215129f25b0b2c7aee5dd74c0f7aeb2ab3
    name: siteconfig-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 605fc9ef0b609efada7ae676e4142ae6d507086d
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-216@sha256:36f536aeb1506b2149651dd68ed06846a8fdecfa1f5c8440ba887fa0ec192642
    name: insights-metrics-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3260e625b844d64fde64747d65a596d3c9d9cd57
        url: https://github.com/stolostron/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-216@sha256:d2e7dae21984d66e6f4ad4c4380a64293e69bbeb9cbe099b465de9861e95ebc7
    name: klusterlet-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0e723e55e1cc08c5760be7d66f4db1910c73b08b
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-216@sha256:7909a5eb9194bb4c5c5f8b2a97852174e097f10e17d5455ca516695ec3d68616
    name: search-collector-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 95972870f9caa2b81b49558c7d8ec523b5e4703b
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-216@sha256:c66f65caebe1398f56d178358812e909d156c89a249bdcc3eec9cfa8e6adbfbf
    name: console-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 24fdaab5152b7609e8de3093322a9c39a3dcabde
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-216@sha256:6c726950d3d380cc46e926cc5338d6fc2d9e9cb1789da75b44e2a32ebbd909e0
    name: search-v2-api-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1df5634cc09a3eb7257b5f5d02c5ad01d3b3d295
        url: https://github.com/stolostron/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-216@sha256:277e2546dd5523114a060625447aba92c52c5906c77699a7f8f14b23465e51f9
    name: search-v2-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c67352e80db2c462de883f0484a3c8d550fdbb90
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-216@sha256:9c173e37b35b1a9179ac605c8286225d19843d7a93c6b8e29a13835f7b721f8a
    name: search-indexer-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1a8948b97bd3ba4517dcb280122aa5de8ec54693
        url: https://github.com/stolostron/search-indexer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-216@sha256:bccb3c83522a7ea9903bc99cab316b2f83707eff540d4dafcc02e971d0acaed0
    name: volsync-addon-controller-acm-216
    source:
      git:
        revision: 4298b79e1fe3b7f2df4e731c169cd6979996481f
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-216@sha256:c23d87fd421c7389d2509a2257c6bebed4cc6eb051b1bbc8642dc9954bb37dd7
    name: cluster-backup-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e26adc44012ec614ca8c5b97e157435c47294b24
        url: https://github.com/stolostron/cluster-backup-operator
status:
  conditions:
  - lastTransitionTime: "2025-11-07T14:25:06Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-11-07T14:25:42Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-07T14:25:42Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-07T14:25:42Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
