apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/mtv-integrations?rev=daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    build.appstudio.redhat.com/commit_sha: daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "85503703441"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-rbfyef
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/mtv-integrations-acm-51-on-push-tkglj
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-5.1"
    pac.test.appstudio.openshift.io/original-prname: mtv-integrations-acm-51-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/mtv-integrations
    pac.test.appstudio.openshift.io/repository: mtv-integrations-acm-215
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    pac.test.appstudio.openshift.io/sha-title: 'fix(plan): set blockOwnerDeletion=false
      to avoid finalizers RBAC error (#367)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/mtv-integrations/commit/daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    pac.test.appstudio.openshift.io/source-branch: main
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: mtv-integrations
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-07-06T23:46:47Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'kube-state-metrics-acm-51,
      node-exporter-acm-51, prometheus-config-reloader-acm-51, observatorium-operator-acm-51,
      obo-prometheus-operator-acm-51, multicluster-observability-operator-acm-51,
      prometheus-operator-acm-51, multicluster-observability-addon-acm-51, metrics-collector-acm-51,
      memcached-exporter-acm-51, thanos-receive-controller-acm-51, grafana-dashboard-loader-acm-51,
      endpoint-monitoring-operator-acm-51, prometheus-acm-51, thanos-acm-51, kube-rbac-proxy-acm-51,
      observatorium-acm-51, grafana-acm-51, rbac-query-proxy-acm-51' is(are) not included
      in snapshot due to missing valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-51-release-acm-51-20260706-233633-000":{"lastUpdateTime":"2026-07-06T23:47:47.94561358Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1783380993000"
    test.appstudio.openshift.io/result-chains-git-commit: daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/stolostron/mtv-integrations
    test.appstudio.openshift.io/result-image-digest: sha256:7cb246245b4d7f04528bfd516d6021083df3f806d2d523671d37284936dc6453
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-51:daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/mtv-integrations
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-51","status":"BuildPLRInProgress","lastUpdateTime":"2026-07-06T23:47:47.94561358Z","details":"Integration
      test passed with warnings","startTime":"2026-07-06T23:46:48.160506479Z","completionTime":"2026-07-06T23:47:47.94561358Z","testPipelineRunName":"enterprise-contract-acm-51-2ghgl"}]'
  creationTimestamp: "2026-07-06T23:46:48Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-51
    appstudio.openshift.io/build-pipelinerun: mtv-integrations-acm-51-on-push-tkglj
    appstudio.openshift.io/component: mtv-integrations-acm-51
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "85503703441"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: mtv-integrations-acm-51-on-push
    pac.test.appstudio.openshift.io/repository: mtv-integrations-acm-215
    pac.test.appstudio.openshift.io/sha: daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: mtv-integrations
    test.appstudio.openshift.io/pipelinerunfinishtime: "1783381602"
    test.appstudio.openshift.io/type: component
  name: release-acm-51-20260706-233633-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-51
    uid: ec6e13f5-affe-47ff-9636-8502a9217f2e
  resourceVersion: "9750377551"
  uid: 353bd73e-e2d3-4c8b-8a32-9efd9ce5aae6
spec:
  application: release-acm-51
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-51@sha256:347b15b2ae84ba5fc0a65ce5ed14298eaa85cf1a1c2e58333bbce4a2b7134633
    name: console-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 604e70a14515a5e0062a6992e6738faf61795b5d
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-51@sha256:67f1b6d0b706fd591dcc5eaa9f0d30d68fe6d5e17b6deedddd438978dcf5af6a
    name: search-v2-api-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4c973a26e653b73735c9e2acf43ec222e12e7a5d
        url: https://github.com/stolostron/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-alertmanager-acm-51@sha256:1b125f4d18e622253181c9672b5c44dd9f7aa60bd4e7458e5df301807fd1d1e5
    name: prometheus-alertmanager-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: f233768f15050e6f1cb7325ff916f0551c20d9e0
        url: https://github.com/stolostron/prometheus-alertmanager
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller-acm-51@sha256:9c9927626d60b99a7efe57d647d1f272576820dc6435604b6fd698f0a4fd173f
    name: governance-policy-addon-controller-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b9e21de7d0316495af98a82aafc8f509bcb4fb6f
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-51@sha256:938758349f61b819eef39f9048fd1c9ae638ee863f359b1bee72975ab4c67033
    name: klusterlet-addon-controller-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1d339b7d8f4f8ca6a952f1701f6cc4df8b9d6912
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/submariner-addon-acm-51@sha256:753f06c6676066132709b91c5ad1b38fb81296a1cbd50cac6a364d1c379cdac9
    name: submariner-addon-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.konflux
        revision: f9e627854f63038ff99fa39d417eeda4b08379b9
        url: https://github.com/stolostron/submariner-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-51@sha256:82d004d5e74c5e502ef3a5599532ec4bae1cf40b0b16faff7f2099e4d92eee43
    name: insights-metrics-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b3572665a8ec5ecc53286360b48e059cb4c2c80e
        url: https://github.com/stolostron/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-51@sha256:7cb246245b4d7f04528bfd516d6021083df3f806d2d523671d37284936dc6453
    name: mtv-integrations-acm-51
    source:
      git:
        context: ./
        revision: daf1f850d7ac502823d4c3fca8f39fb5b72f2d82
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/must-gather-acm-51@sha256:feb03a754ebccf99e2479ea240867374c4c5dac27043f92bd08ef8652ff93ea8
    name: must-gather-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 267901f266c43ddc03c524a72ee319c263845c8f
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-51@sha256:cc9bcfad89bd762a5b90a6673c2e97e3c7e179a53bbff74f039cca6df63f2517
    name: multicluster-role-assignment-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 65f0b1b537f78ab848d0d9e7a4e50d804d1d7625
        url: https://github.com/stolostron/multicluster-role-assignment
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-51@sha256:76a0ff040491497c29f085361f4e95f7954edd2aafad921f90e000ad7f680919
    name: volsync-addon-controller-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 193e92b6207660e4a2a91f1c0ce9c39902ce314d
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-channel-acm-51@sha256:f03e4b91c99c5226bca772c34e0e7041cad200c1282a844dcca40b8c6af5cc65
    name: multicluster-operators-channel-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: dfa39a88a606dafaf1bc35400173c2dc2ceb11d1
        url: https://github.com/stolostron/multicloud-operators-channel
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-51@sha256:33559fc27050bc79d9375f1526c771a51189cb079a76000cffefcda830f59619
    name: insights-client-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 69ed42a45107debeb026c30390ad93c85c2e6855
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-propagator-acm-51@sha256:67a717f137427d244e0b12e58198d13dce6894c0f39b118c48297e03b61baed1
    name: governance-policy-propagator-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 58ab5507fafe53faa956ac7f4d85147791c644e3
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-51@sha256:3aaeb3f8151a3feee3b00e6f8a0ab12c11a35f2742c6eaa101ff498ad7cb1910
    name: search-v2-operator-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fcbd6203e89abd81f2239d6962090dcbdd3bb754
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-application-acm-51@sha256:61f4e0bbc184b67bbc07f40143f24aeaa4a480f78fbe556f7fbc6d6efa8966c4
    name: multicluster-operators-application-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7b3086617a2c877b22c44334e72d76067182ae75
        url: https://github.com/stolostron/multicloud-operators-application
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-51@sha256:9b6711cee79a9d8529557b70806ffd4c50a162d2848726100a409453d0078485
    name: multicloud-integrations-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2610cd1591a51b91cfcfd4430711cec398e9a260
        url: https://github.com/stolostron/multicloud-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-51@sha256:36fb46075876234ed1687e4fde8e3769ebb62d2cb1ca006c275256d68df8c6be
    name: search-collector-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 63701e7b17c94ef260d4f0ece0cc81ea4cbb937a
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cert-policy-controller-acm-51@sha256:cc89a8f26aefcd176abec4b04912c6851324e501e242c600f1a216812b484a0e
    name: cert-policy-controller-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 048b8e502c58aaa9d367da1257be24bb81259c38
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-51@sha256:fcd9423557362fec895aed0b556d6fcab5c1672f7eb88fef12b168ebe896bf44
    name: cluster-backup-operator-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 715e09acc0172870b096596d0b5bc83cb60523e9
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-51@sha256:482d4ae409cca233bba92a2595517eb38acfdf7aa6918309206d348eaa53920a
    name: multiclusterhub-operator-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 493c348e6ef2c5d37ac20c473c1e1001ee0a4f0e
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-framework-addon-acm-51@sha256:c08728b3f721f44c756db1dc0d431405ee066beea547a3b50a3fbb3b2e868f2c
    name: governance-policy-framework-addon-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 51fc034e02a24aef579b0b225f929a0a725979da
        url: https://github.com/stolostron/governance-policy-framework-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-51@sha256:72e3cb36e0aa2cb77feb988831f881d805b018c8ca1adba88b01a5d96e5cbbbf
    name: search-indexer-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9c843dddd655a153025d834e2b526d4eda2270c7
        url: https://github.com/stolostron/search-indexer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-subscription-acm-51@sha256:1b6ada9981dec6b4d5c6860b648b938b926a86de6c5afc4f592634471f4e351f
    name: multicluster-operators-subscription-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 6b271061ab3723aaaf01936b132e8248895d672f
        url: https://github.com/stolostron/multicloud-operators-subscription
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/acm-cli-acm-51@sha256:de2a960033be7eac5a9e89d6f32679d184d0c9e659137d442e2054237a3d4b84
    name: acm-cli-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 692c4e4620f2846b905cca24e77a421c86e3931f
        url: https://github.com/stolostron/acm-cli
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-51@sha256:66f31eb0b2eba7ce58af59b13210bb56a12cf45f064201b43f441167b1f47516
    name: siteconfig-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: cda5870924d4c726f9658bf4b948c73082285d48
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller-acm-51@sha256:f0b810a982884fb81c57edab86633636bebb5db2cd4b4ca3f001807cf7bda94e
    name: config-policy-controller-acm-51
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 3a5704d7527936777c7dddb218e8ae6d37313fdd
        url: https://github.com/stolostron/config-policy-controller
status:
  conditions:
  - lastTransitionTime: "2026-07-06T23:47:49Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-07-06T23:47:49Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-07-06T23:47:49Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
