apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicloud-integrations?rev=8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    build.appstudio.redhat.com/commit_sha: 8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "102232797539"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-welvrg
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/multicloud-integrations-acm-52-on-push-pxr42
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "main"
    pac.test.appstudio.openshift.io/original-prname: multicloud-integrations-acm-52-on-push
    pac.test.appstudio.openshift.io/pull-request: "608"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicloud-integrations
    pac.test.appstudio.openshift.io/repository: multicloud-integrations-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: xiangjingli
    pac.test.appstudio.openshift.io/sha: 8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    pac.test.appstudio.openshift.io/sha-title: |-
      Add Tekton files for versions: 5.1 5.2 (#608)

      Remove 2 stale Tekton file(s) for version <= 5.0

      Signed-off-by: OpenShift CI Robot <noreply@openshift.io>
      Co-authored-by: OpenShift CI Robot <noreply@openshift.io>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicloud-integrations/commit/8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    pac.test.appstudio.openshift.io/source-branch: refs/heads/main
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-integrations
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-integrations
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-09-08T21:01:48Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'kube-rbac-proxy-acm-52,
      dynamic-scoring-addon-acm-52, metrics-collector-acm-52, multicluster-observability-operator-acm-52,
      prometheus-alertmanager-acm-52, cluster-permission-acm-52, rbac-query-proxy-acm-52,
      grafana-acm-52, multicluster-observability-addon-acm-52, obo-prometheus-operator-acm-52,
      thanos-receive-controller-acm-52, node-exporter-acm-52, prometheus-acm-52, prometheus-config-reloader-acm-52,
      observatorium-operator-acm-52, kube-state-metrics-acm-52, endpoint-monitoring-operator-acm-52,
      observatorium-acm-52, grafana-dashboard-loader-acm-52, thanos-acm-52, memcached-exporter-acm-52,
      prometheus-operator-acm-52, dynamic-scoring-controller-acm-52' is(are) not included
      in snapshot due to missing valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-52-release-acm-52-20260908-205025-000":{"lastUpdateTime":"2026-09-08T21:02:47.784548297Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1788900625000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/result-chains-git-commit: 8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/stolostron/multicloud-integrations
    test.appstudio.openshift.io/result-image-digest: sha256:9e5ed21d1adb8c852a45589a480ef5aa751ec0ed6b459744a3fe52a445b80b97
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-52:8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-integrations
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-52","status":"BuildPLRInProgress","lastUpdateTime":"2026-09-08T21:02:47.784548297Z","details":"Integration
      test passed with warnings","startTime":"2026-09-08T21:01:49.231673945Z","completionTime":"2026-09-08T21:02:47.784548297Z","testPipelineRunName":"enterprise-contract-acm-52-7k4dv"}]'
  creationTimestamp: "2026-09-08T21:01:49Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-52
    appstudio.openshift.io/build-pipelinerun: multicloud-integrations-acm-52-on-push-pxr42
    appstudio.openshift.io/component: multicloud-integrations-acm-52
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "102232797539"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multicloud-integrations-acm-52-on-push
    pac.test.appstudio.openshift.io/pull-request: "608"
    pac.test.appstudio.openshift.io/repository: multicloud-integrations-acm-210
    pac.test.appstudio.openshift.io/sha: 8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-integrations
    test.appstudio.openshift.io/pipelinerunfinishtime: "1788901294"
    test.appstudio.openshift.io/type: component
  name: release-acm-52-20260908-205025-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-52
    uid: cfc033ef-9dfc-426e-9763-dbb135f75288
  resourceVersion: "11056708475"
  uid: 993ec3e0-091e-4096-8d51-628111fbe8f1
spec:
  application: release-acm-52
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-52@sha256:81802e71357e07dad1309e3511a918d7d58457cca2d1884e55597ef44536c58a
    name: klusterlet-addon-controller-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5341d7699a6da19b5cae586faa0a4829d5cfdb48
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/submariner-addon-acm-52@sha256:43aa73c8920c8c9805a134176c1ee4d181bacab7c9bad4ab4da96ad082d136e7
    name: submariner-addon-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.konflux
        revision: e31ca93ba9da5ee6d2f29439080a247408c61464
        url: https://github.com/stolostron/submariner-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-52@sha256:34bfee21dc759857136c84d26074093832a392d1f44a5cc2cf321523017c08d4
    name: multiclusterhub-operator-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2c9b8c616edae22008cb9788014850f9178e9987
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-framework-addon-acm-52@sha256:1c3209f3e9562f606b1dc70b1f74a3dc0fcdc1284341037956f75d9b28a76fc8
    name: governance-policy-framework-addon-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b015e2fd48ff7d96251a662a2a507a4c4c72b818
        url: https://github.com/stolostron/governance-policy-framework-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-52@sha256:7edf73d534189bde375b3a5f7a7517f8ced66761bf18a4aebd89005353ec8e64
    name: mtv-integrations-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 3595ff4bb5048837d27d95f7bc07f415bbcb97e7
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller-acm-52@sha256:085d3b7e48ece7b5f317b7021d3dabeec2f0bdd7bdbc19442d1b31771f8ef4be
    name: config-policy-controller-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 32c0aa0faca3ab97c55b2be45cbe550886be4a5d
        url: https://github.com/stolostron/config-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-52@sha256:e7eefe9c8dd525ce543fdb078d8360386d557cb5a9a51ddb84a8a78730fc13b0
    name: console-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 4d4ff40c408ccb5c03db3af66e38a43ccd5d8548
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-application-acm-52@sha256:d6a538b789e013a942314dc32093aed89e51603eb4e25874473d01819dc35f95
    name: multicluster-operators-application-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: d2e4f912b578e584a9b4d77b1732cc641b60697e
        url: https://github.com/stolostron/multicloud-operators-application
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-52@sha256:539cf3ef23bfccebb442e2e8feeac1b0e9415f0543659fe48f5a05ab994ff8d3
    name: volsync-addon-controller-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dadcfce09515bc36dce2b6a7d053d855e2b8fb66
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-52@sha256:5508031a545478b9f0f6b4ab77360fa82a902aee9ca402694fc72693d37501e7
    name: insights-client-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 51be1dcc75a7503f02ece13b831dfa5a2ae7e136
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cert-policy-controller-acm-52@sha256:5d49fe140af086f56e5f01bf562144b2f4fc391fa599905c950e12220eab5c34
    name: cert-policy-controller-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 35c1e5befacfe8fe15240faeaac6e7f29bdcf193
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/acm-cli-acm-52@sha256:e563d31923a23359e11e6ba21357a85de6dc680e5d8ff1a5fbf851bd979ec85c
    name: acm-cli-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a34137782cc73cc1548d4d7a09298131c1d73f14
        url: https://github.com/stolostron/acm-cli
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-52@sha256:900c055053c1ffc72d03e161cf2ef34ae127e035fb29ae2669f202175e7a20a0
    name: search-collector-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9bd560ce5659c60c8b681f18e234f306488ae4db
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller-acm-52@sha256:6068c9573ff057413368415889ecac25eda96dbfbc6a485d96fde6cd4b72d3f8
    name: governance-policy-addon-controller-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 752a0920ba5da9d490ab0eabe775a78b632270f7
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-52@sha256:a6212e965a5cd035d1730e7547a8a571d1fa33df6c55bccded83b87a95aba601
    name: multicluster-role-assignment-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 412969c578f0ab7eeea2951e8170b0da204190be
        url: https://github.com/stolostron/multicluster-role-assignment
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/must-gather-acm-52@sha256:7a817e470e55ecc28976bf45ab777b4c602151f38f2384e692687509a445e141
    name: must-gather-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 203e21767f29c24069a92565638befed9fc7cc41
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-52@sha256:b609ce832ca43a0cbee61189e735b21350b93816ded2536d3e886fe2c2f6d0ce
    name: siteconfig-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7e87f0dcf04bfafa8cbb20b3ab9b4a3626a9843e
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-52@sha256:9e5ed21d1adb8c852a45589a480ef5aa751ec0ed6b459744a3fe52a445b80b97
    name: multicloud-integrations-acm-52
    source:
      git:
        context: ./
        revision: 8e734c1f1cecb86c87b6b01e67d4ad0568e4f823
        url: https://github.com/stolostron/multicloud-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-52@sha256:04b7c92f00743a23b1abbb58ec85125c5181bf3ddaf42fae16dbca53e1146dfe
    name: search-v2-operator-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6c09831508e46ac30deb706329f2ce3cd58d18df
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-52@sha256:3c060e6251d0fe665e9cb4c7b6dc20147461ffc008b1383d91e0d3ed8cccc6c1
    name: search-indexer-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f3c7e2363b36fe84a67e4b05673e1cc9b694dcb4
        url: https://github.com/stolostron/search-indexer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-52@sha256:445839646307cd96d0d9aa5b1572366a65193bd079ef8c9fa56877aa683d4025
    name: cluster-backup-operator-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3e3e40053e9cd6d0cb9218281f59d94b34c9874a
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-52@sha256:eb3727e2b579c520a00d7e0f830d3fe8e77c84af29d65345ef238624a94ed3d9
    name: search-v2-api-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 50f9bee703c60d685bb7f4b2fc8597a0337e6e04
        url: https://github.com/stolostron/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-channel-acm-52@sha256:a57da029527aa34a5e5e2d5b551cd82adc971b2fa95acbf8e1d65e8ee555b16a
    name: multicluster-operators-channel-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b6d85bd6fc0f27627b79856dbdc942b7e60ffd75
        url: https://github.com/stolostron/multicloud-operators-channel
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-propagator-acm-52@sha256:eea210046c067fc81f510deb8d23fa996337d36e8d1b4ca01e27546b72d53d24
    name: governance-policy-propagator-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 5986d8a9a9fee336a1f987eaf3e32a1e6ab91633
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-subscription-acm-52@sha256:5d02af8a17e381c95b805c6a8466e9fcf592c40967e41e6f2777899e0872a0b8
    name: multicluster-operators-subscription-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1d23cf208fcc1f8685ca5acd0bd5b28010c91022
        url: https://github.com/stolostron/multicloud-operators-subscription
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-52@sha256:d2197763bb83573d90dfd79038a1038b16bba0e653c4b12dbf2080c0f7f3b5bb
    name: insights-metrics-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e33c54792c15ac5ba1a91e3a38d0d54b2c22de0d
        url: https://github.com/stolostron/insights-metrics
status:
  conditions:
  - lastTransitionTime: "2026-09-08T21:02:47Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-09-08T21:02:47Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-09-08T21:02:48Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
