apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicluster-role-assignment?rev=57c73e9263314c329e4c81b04e8bab4951c019ab
    build.appstudio.redhat.com/commit_sha: 57c73e9263314c329e4c81b04e8bab4951c019ab
    build.appstudio.redhat.com/target_branch: release-2.16
    pac.test.appstudio.openshift.io/branch: release-2.16
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "55145189181"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-tgackc
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/multicluster-role-assignment-acm-216-on-push-ds79d
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.16"
    pac.test.appstudio.openshift.io/original-prname: multicluster-role-assignment-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "173"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicluster-role-assignment
    pac.test.appstudio.openshift.io/repository: multicluster-role-assignment-acm-215
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 57c73e9263314c329e4c81b04e8bab4951c019ab
    pac.test.appstudio.openshift.io/sha-title: Update module golang.org/x/term to
      v0.37.0 (#173)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicluster-role-assignment/commit/57c73e9263314c329e4c81b04e8bab4951c019ab
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.16
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicluster-role-assignment
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicluster-role-assignment
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-11-12T03:37:58Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'governance-policy-framework-addon-acm-216,
      grafana-dashboard-loader-acm-216, kube-state-metrics-acm-216, multicluster-operators-application-acm-216,
      prometheus-config-reloader-acm-216, kube-rbac-proxy-acm-216, prometheus-alertmanager-acm-216,
      prometheus-operator-acm-216, submariner-addon-acm-216, rbac-query-proxy-acm-216,
      grafana-acm-216, metrics-collector-acm-216, multicluster-observability-operator-acm-216,
      node-exporter-acm-216, observatorium-acm-216, prometheus-acm-216, thanos-acm-216,
      endpoint-monitoring-operator-acm-216, multicluster-observability-addon-acm-216,
      multicluster-operators-channel-acm-216, thanos-receive-controller-acm-216, cluster-permission-acm-216,
      memcached-exporter-acm-216, multicluster-operators-subscription-acm-216, observatorium-operator-acm-216'
      is(are) not included in snapshot due to missing valid containerImage or git
      source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-216-release-acm-216-j4sjx":{"lastUpdateTime":"2025-11-12T03:38:33.90345503Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762918165"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicluster-role-assignment
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-216","status":"TestPassed","lastUpdateTime":"2025-11-12T03:38:33.90345503Z","details":"Integration
      test passed","startTime":"2025-11-12T03:37:58.848493302Z","completionTime":"2025-11-12T03:38:33.90345503Z","testPipelineRunName":"enterprise-contract-acm-216-7df6j"}]'
  creationTimestamp: "2025-11-12T03:37:58Z"
  generateName: release-acm-216-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-216
    appstudio.openshift.io/build-pipelinerun: multicluster-role-assignment-acm-216-on-push-ds79d
    appstudio.openshift.io/component: multicluster-role-assignment-acm-216
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "55145189181"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multicluster-role-assignment-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "173"
    pac.test.appstudio.openshift.io/repository: multicluster-role-assignment-acm-215
    pac.test.appstudio.openshift.io/sha: 57c73e9263314c329e4c81b04e8bab4951c019ab
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicluster-role-assignment
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762918672"
    test.appstudio.openshift.io/type: component
  name: release-acm-216-j4sjx
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-216
    uid: 36e17c1d-3fe4-44ec-96e0-7fac572eda72
  resourceVersion: "5805268084"
  uid: 98a90592-4e10-4c47-a69d-b03e9af8a0b0
spec:
  application: release-acm-216
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-216@sha256:8bf97058b7c29c029cc92e568709300da53afc4964a1de5ff3aa34f8d92220bd
    name: console-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 78e841cd540f8049892a24cfe91d14e04fce2a4f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-216@sha256:ec786c372f0fc592c2484e10fe952732b008fe423ed6159ee159e2c1faf9f8ac
    name: search-indexer-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: be3464b54648070954457daa16d82d963a3d69ea
        url: https://github.com/stolostron/search-indexer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-216@sha256:b0bca20324584e8b9fd4c6bbebb972f46e8ed8caf99850d91469ae3b09c789f0
    name: siteconfig-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 5c7948458a83dd750efc7c73eb995dc2d16d1a6f
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-216@sha256:74e14840ec89a871ee1f473463104f3aabc82149c347fef0fe741e38d0fefe3c
    name: cluster-backup-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2a9e100704fe154e17907ae0abb5310ea0069501
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/acm-cli-acm-216@sha256:3dc11a8646062e23611ed9f83d9490d43f12133c1b95a289a9855ee52f0d783e
    name: acm-cli-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f3e05e5fd1af46f9ca3b03c3a9f6ffebfbff30ae
        url: https://github.com/stolostron/acm-cli
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-propagator-acm-216@sha256:dedef313931717845ef42a0c45d1caf338032fbe6f7e112cd1a88099ee53d877
    name: governance-policy-propagator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2c502c2c859c21bc649a9ee9335bc961197c9a1c
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-216@sha256:506aa32aa43b96f6eb83003228d5facd82a2bb69e013800a39af6611b326a99f
    name: klusterlet-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 31d78023b7f23d35f82eef5f0cb8c58a9e32cc2c
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-216@sha256:9df7d0fbc2ca862ec746b6e315c7f05e7a14e094e5273386c474af9b32412317
    name: multicloud-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 201f0868adf6680655d73338c730a7dedbd37324
        url: https://github.com/stolostron/multicloud-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-216@sha256:277e2546dd5523114a060625447aba92c52c5906c77699a7f8f14b23465e51f9
    name: search-v2-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c67352e80db2c462de883f0484a3c8d550fdbb90
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cert-policy-controller-acm-216@sha256:df6c5854fe6ae32ef2cb06806d57e0da6dbdb4807093edff7a299ebddab675b8
    name: cert-policy-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: e51cc33724db8bb88b37d063225ef649855ca304
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller-acm-216@sha256:d715dca420bdae96cf1c8de026888d799ea383648fbca844c0ae8d0b3b866250
    name: config-policy-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7be13b63c3435e913c61004002041f3586ae0816
        url: https://github.com/stolostron/config-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller-acm-216@sha256:0c33e79fad37fb24ae5f0d250ee4d169c4cddfbb9c28dac532a4fc76362b7471
    name: governance-policy-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2b3cb20c875d3c485751281b870bbe251665326b
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-216@sha256:36f536aeb1506b2149651dd68ed06846a8fdecfa1f5c8440ba887fa0ec192642
    name: insights-metrics-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3260e625b844d64fde64747d65a596d3c9d9cd57
        url: https://github.com/stolostron/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-216@sha256:3f8b4784bcdd6a05757c94a8a5b402e441cfda04b9613bcf4ff2482a0f851a83
    name: mtv-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: c7bfbe48b4e0de377b69c6fefdfd5a40f4615c23
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-216@sha256:8e10b2842bd1e533c78254d526cb6485646d6f08d6930ad8dce0419a9ed3cc11
    name: multicluster-role-assignment-acm-216
    source:
      git:
        revision: 57c73e9263314c329e4c81b04e8bab4951c019ab
        url: https://github.com/stolostron/multicluster-role-assignment
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-216@sha256:460330c8c3e06206f6f15dc2def3f9341adf63720232845fd07fea8e83c2b320
    name: multiclusterhub-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: afad8efdb58a04ab304977e27cefd3268f2c3b78
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-216@sha256:8083f59328e29d240b5af1d50dbe26cb00c30aa4ed57706fe34e7631b1b13c19
    name: search-v2-api-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 741ef9d24b4a7c7eabd2ae62269a9f718b824e25
        url: https://github.com/stolostron/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/must-gather-acm-216@sha256:c443aff1c5edb73cbf2e775b9b075186b118411cd199f7ab5c20f5c588c55e82
    name: must-gather-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 4774a53376e3583ab2364142ccda378f26a048ed
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-216@sha256:7909a5eb9194bb4c5c5f8b2a97852174e097f10e17d5455ca516695ec3d68616
    name: search-collector-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 95972870f9caa2b81b49558c7d8ec523b5e4703b
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-216@sha256:2b6f1e57833aa98d7e0acec558b1da44138b1eed22185bb4459d41463f1cb193
    name: insights-client-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c5a46b852fdcf8d875379289637fa1d93fabb844
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-216@sha256:bccb3c83522a7ea9903bc99cab316b2f83707eff540d4dafcc02e971d0acaed0
    name: volsync-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4298b79e1fe3b7f2df4e731c169cd6979996481f
        url: https://github.com/stolostron/volsync-addon-controller
status:
  conditions:
  - lastTransitionTime: "2025-11-12T03:38:33Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-12T03:38:33Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-12T03:38:34Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
