apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    test.appstudio.openshift.io/group-test-info: '[{"namespace":"crt-redhat-acm-tenant","component":"insights-client-acm-211","buildPipelineRun":"insights-client-acm-211-on-pull-request-v9pr7","snapshot":"release-acm-211-59gbl","repoUrl":"https://github.com/stolostron/insights-client","pullRequestNumber":"592"},{"namespace":"crt-redhat-acm-tenant","component":"insights-metrics-acm-211","buildPipelineRun":"insights-metrics-acm-211-on-pull-request-qp8sl","snapshot":"release-acm-211-8f6sr","repoUrl":"https://github.com/stolostron/insights-metrics","pullRequestNumber":"478"},{"namespace":"crt-redhat-acm-tenant","component":"search-collector-acm-211","buildPipelineRun":"search-collector-acm-211-on-pull-request-tfb2q","snapshot":"release-acm-211-q4vfv","repoUrl":"https://github.com/stolostron/search-collector","pullRequestNumber":"791"},{"namespace":"crt-redhat-acm-tenant","component":"search-indexer-acm-211","buildPipelineRun":"search-indexer-acm-211-on-pull-request-sm7mc","snapshot":"release-acm-211-tjkb6","repoUrl":"https://github.com/stolostron/search-indexer","pullRequestNumber":"623"},{"namespace":"crt-redhat-acm-tenant","component":"search-v2-api-acm-211","buildPipelineRun":"search-v2-api-acm-211-on-pull-request-rm7g5","snapshot":"release-acm-211-bpms2","repoUrl":"https://github.com/stolostron/search-v2-api","pullRequestNumber":"637"}]'
    test.appstudio.openshift.io/pr-group: 2-11-go-1-24
  creationTimestamp: "2025-09-03T16:09:19Z"
  generateName: release-acm-211-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-211
    pac.test.appstudio.openshift.io/event-type: pull_request
    test.appstudio.openshift.io/pr-group-sha: 4e79515e6af846777e12514832b3f7ba72a60c110bc787b4ee4bf325681ee8
    test.appstudio.openshift.io/type: group
  name: release-acm-211-8zkjr
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-211
    uid: af4ac5ff-3f9a-4f13-b93b-0e6b207eecb9
  resourceVersion: "4970889770"
  uid: 9c0d4952-226a-4d1c-8644-a28d0152062d
spec:
  application: release-acm-211
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/volsync-addon-controller-acm-211@sha256:8319c58051adbfd7669148032f1665e5576d10bd31176b6ef9901babd3ba684c
    name: volsync-addon-controller-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 52ed53ca9fab862ec23401cf4c4ee620015264e9
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/cert-policy-controller-acm-211@sha256:b5390a834958118060947809b32726e77ecf2283b9ba88270db398f8c8e1e11f
    name: cert-policy-controller-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1325c07c54f7f301a7ca717d5f3d0d2d66ce71a4
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/governance-policy-addon-controller-acm-211@sha256:d67862ea2b31381402130269addb5c23e8700a5f6c0a77d2e39b189b45f2e15e
    name: governance-policy-addon-controller-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: ebe19a309090e6464edc944ea0cd039e7b2f7072
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/grafana-acm-211@sha256:e86fed52c64def2106fbe0c5e672983d61cb57d80243400409c5b5c771548482
    name: grafana-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 7718312d983d94930a6b9ea7d6212f0d12ead02b
        url: https://github.com/stolostron/grafana
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/prometheus-acm-211@sha256:7649b1727d496bcf5496dcbd8ba0ca57b9dde9caf53f2974eccbd8e49a628505
    name: prometheus-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: ce00e8c7939f7c045fb7ef6bb9896200054ea0e1
        url: https://github.com/stolostron/prometheus
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/prometheus-operator-acm-211@sha256:d6903f5d55e21d29f195ea156ed88e4c3fb4f43c3b0fe45ea2aab7ae1d3d3b50
    name: prometheus-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: b29f89a7df4b63610622af73bd7e822827ccd6a5
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/search-v2-operator-acm-211@sha256:4948459f37d8108427b9b2d7bbd2ffb355e1a93584be1712315d68cf01c1f5ef
    name: search-v2-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 75aaf451a906996c750ccaf71cc2aae539c557f3
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/thanos-acm-211@sha256:a468ce51665844ab623c24604017dcaa6b71a6e68941ee2f43a7a002f5894b16
    name: thanos-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 4efe4981cb5a474a35d8ade272aef087edb9bc28
        url: https://github.com/stolostron/thanos
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/endpoint-monitoring-operator-acm-211@sha256:e2ce019a2a18480ef867756b85a6706c88ff94777aac4b2b539789c10b551d55
    name: endpoint-monitoring-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: operators/endpointmetrics/Containerfile.operator
        revision: 516ee2d3da88357362fbe6c0bdb5434af5d596d4
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/insights-client-acm-211@sha256:2ded2b116f650b8d3bc125a7861266ecac4a772f2f43b11a8f9ebb5e833226b8
    name: insights-client-acm-211
    source:
      git:
        revision: f88d7186432550b3ba5fb922b51b85e2f5365d13
        url: https://github.com/smcavey/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/metrics-collector-acm-211@sha256:b2d6efd263b44359a5706d22e3ecc85dbc34eec750176fb5cb37272c9f9ac118
    name: metrics-collector-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: collectors/metrics/Containerfile.operator
        revision: 516ee2d3da88357362fbe6c0bdb5434af5d596d4
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/node-exporter-acm-211@sha256:5db417902c052f14b8dc4bfc32515c18ee536b008b5051b3323487f7303d7706
    name: node-exporter-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 3614db875dd98db04e6bc211f25512d814a5b4f1
        url: https://github.com/stolostron/node-exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/insights-metrics-acm-211@sha256:817d78559b2f46efdc42e19daec3925bd219f06c87c54956331764d67dbbed97
    name: insights-metrics-acm-211
    source:
      git:
        revision: 0091ffa981e51a4c1269b8f021121845a0af7c9e
        url: https://github.com/smcavey/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/klusterlet-addon-controller-acm-211@sha256:bd9d502d1dc6571bd328a2c8cbcdadde2b83982c0d82c9d40ba7093bfe3c73c0
    name: klusterlet-addon-controller-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3d0ebda4b74e9a3194fba12b289bff60865e1108
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/observatorium-operator-acm-211@sha256:60089554d1e94550e11f4fe8f7b221c0787659c95c7bff5d57dadad8232f9b21
    name: observatorium-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: b8c1f6b44930cecc7483b24d7135106a86f2a398
        url: https://github.com/stolostron/observatorium-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/search-collector-acm-211@sha256:885f6e7bcc676d05bdc2829a7c78f077a839eb3398be2b62951eaed976c5a121
    name: search-collector-acm-211
    source:
      git:
        revision: 6285b03210df6a56e50d81a984a51c5186dfe8c7
        url: https://github.com/smcavey/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/cluster-backup-operator-acm-211@sha256:391d306c97abb099e27fe30db27f45f29f849bb638a52c153c083511425b45cc
    name: cluster-backup-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1e0c4ee2fccf9e70629eff07cc5b9daf0e091fca
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/console-acm-211@sha256:ccec5411ab453844eb2015077a093daa6bc1a447d6f3e07dd29a776c51e20b3d
    name: console-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 042cb69e17448fb7308bf998b9ae4deae84ab3cf
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/multicluster-observability-operator-acm-211@sha256:8bd605f8e11dbd448f393cfc6da9fe90ffcf5a90ccadfa16c2f87866a264dea9
    name: multicluster-observability-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: operators/multiclusterobservability/Containerfile.operator
        revision: 516ee2d3da88357362fbe6c0bdb5434af5d596d4
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/observatorium-acm-211@sha256:f1c90874c3185828708cd15fc240f98ec4736d3cb0ba77c874c0b403fb009ec9
    name: observatorium-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: d7d07ba199a860d679bb88b1e91155688522d8f6
        url: https://github.com/stolostron/observatorium
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/search-indexer-acm-211@sha256:663f32b41d5aa1b6cdbb7ec28e168231c787d2273346a139d2e1537f27dd6df9
    name: search-indexer-acm-211
    source:
      git:
        revision: 91f6c35c63ba192d42e593f940013f0aaf988049
        url: https://github.com/smcavey/search-indexer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/governance-policy-propagator-acm-211@sha256:c378a15ca4b9730455045be4a8a9790b479ecbe50156cabed0a67afb5876c5bb
    name: governance-policy-propagator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 3ca26f0712237236299771fc646766462053e39b
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/memcached-exporter-acm-211@sha256:cbbede80dc5527f3763e5011fbdd9471e343129f829045775579c6dca7331975
    name: memcached-exporter-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 3812453f98e444e6d14063cb1a9ca6b4e85deb8e
        url: https://github.com/stolostron/memcached_exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/rbac-query-proxy-acm-211@sha256:cae60d3a8bed5b46487de05ab4ba5428ddaf666b412596b65681cda36ddf0588
    name: rbac-query-proxy-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: proxy/Containerfile.operator
        revision: 516ee2d3da88357362fbe6c0bdb5434af5d596d4
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/kube-rbac-proxy-acm-211@sha256:0c214c3ecaed2b65e76d4dc7ece891df141b6fb62d3ccf52c2ff6f99bcf73ab4
    name: kube-rbac-proxy-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 885db415edb2e4f7cbea430cb22dd8bcafae0664
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/multiclusterhub-operator-acm-211@sha256:b5229cb74128571802c05e1b96d9f4d6bc11f7d6d42933ddb727b3b1b99cd625
    name: multiclusterhub-operator-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 50345af65b1cf514562a996da6d93bb446ef2bf0
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/must-gather-acm-211@sha256:5ca14bbba84afb8dfdd49d54cd05620833fbfdbef11bbd5ff128d376c653728d
    name: must-gather-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 0e542533f2eabf26bd704fb1d2da5b46845eef8a
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/prometheus-config-reloader-acm-211@sha256:8ff5c462ae550c9a195953a091448d443e02a81a162f0c639f8f92879c6db61b
    name: prometheus-config-reloader-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: cmd/prometheus-config-reloader/Containerfile.operator
        revision: b29f89a7df4b63610622af73bd7e822827ccd6a5
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/search-v2-api-acm-211@sha256:a9b95d5f24b237b531b1a06bff4899ec2d8461e2d117dff9cd66b978aa96a24b
    name: search-v2-api-acm-211
    source:
      git:
        revision: 1f5dc5981b75038ab2b00db4509ad0c1f08bc5f0
        url: https://github.com/smcavey/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/thanos-receive-controller-acm-211@sha256:5659f0f28e5bedb9ae71b9fabcc594ed40339444ec8f527ac1b1029a100ceb73
    name: thanos-receive-controller-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 3f438fb201e115a5dd8046ded77be5cbf9fed1de
        url: https://github.com/stolostron/thanos-receive-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/config-policy-controller-acm-211@sha256:fa3486be377c0fda138159a00962705f616a1fa7ffe7c767432859072a66a822
    name: config-policy-controller-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 989e477069519c62f1833b9dada64fae297fa2f1
        url: https://github.com/stolostron/config-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/grafana-dashboard-loader-acm-211@sha256:a5b3280749d9871c2d6526c5b890c9120f81325876d9e3cd8f17a964ef17abd4
    name: grafana-dashboard-loader-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: loaders/dashboards/Containerfile.operator
        revision: 516ee2d3da88357362fbe6c0bdb5434af5d596d4
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/kube-state-metrics-acm-211@sha256:0b8a6571895020ca0a9a907c0acb776e6fc59c7da35f3d61046a9e6b12ba15ab
    name: kube-state-metrics-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: c86a8858c06aad269b2da5f63f4e4e359aae529e
        url: https://github.com/stolostron/kube-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/multicluster-operators-application-acm-211@sha256:fadeba5592f06468d3408abb71abbf170ffb92d811aae96cf9d824776f619e7e
    name: multicluster-operators-application-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: f576ff4fbbfd55f828a2c3d41c09272521404e7d
        url: https://github.com/stolostron/multicloud-operators-application
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/prometheus-alertmanager-acm-211@sha256:3c9fd115db621e6c2ed308fc190c132042933bf0b85d7c87f4b3935e5d8c5e7d
    name: prometheus-alertmanager-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: f2a62ba11026d261fb5ff1c1f9907eacffb57293
        url: https://github.com/stolostron/prometheus-alertmanager
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/governance-policy-framework-addon-acm-211@sha256:b3ec4720ac7b5ea5706d001d7e7aa9893d7d07ee2f8381cacb2ca91170e1aac5
    name: governance-policy-framework-addon-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 6608c146159010846f2f818e98c075ac971bcc07
        url: https://github.com/stolostron/governance-policy-framework-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/multicluster-operators-subscription-acm-211@sha256:faaa836f5f8e34f4b34ea38a6e64b8d0bc872f1cacc6c273435a8e11c5ab98d8
    name: multicluster-operators-subscription-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1498c85977986dddd4057c3f21f98658d562ad96
        url: https://github.com/stolostron/multicloud-operators-subscription
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-211/submariner-addon-acm-211@sha256:c2f55e78cc2ff302d8afdf68d99feb5933b8378645e70e3cba81b2d3b96f43ba
    name: submariner-addon-acm-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.konflux
        revision: 4eded24aea8ad687b2cbb885376098f4d627976b
        url: https://github.com/stolostron/submariner-addon
status:
  conditions:
  - lastTransitionTime: "2025-09-03T16:09:20Z"
    message: No required IntegrationTestScenarios found, skipped testing
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
