apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/siteconfig?rev=c78923c118ecb8f169537c9ce14a13cef3eae517
    build.appstudio.redhat.com/commit_sha: c78923c118ecb8f169537c9ce14a13cef3eae517
    build.appstudio.redhat.com/target_branch: release-2.17
    pac.test.appstudio.openshift.io/branch: release-2.17
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "63696550078"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-hzzdhb
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/siteconfig-acm-217-on-push-cgfdr
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.17"
    pac.test.appstudio.openshift.io/original-prname: siteconfig-acm-217-on-push
    pac.test.appstudio.openshift.io/pull-request: "891"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/siteconfig
    pac.test.appstudio.openshift.io/repository: siteconfig-main
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: c78923c118ecb8f169537c9ce14a13cef3eae517
    pac.test.appstudio.openshift.io/sha-title: |-
      NO-ISSUE: Update module github.com/grpc-ecosystem/grpc-gateway/v2 to v2.27.8 (#891)

      Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>
      Co-authored-by: red-hat-konflux[bot] <126015336+red-hat-konflux[bot]@users.noreply.github.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/siteconfig/commit/c78923c118ecb8f169537c9ce14a13cef3eae517
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.17
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/siteconfig
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: siteconfig
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-16T01:11:57Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'search-v2-api-acm-217,
      config-policy-controller-acm-217, must-gather-acm-217, governance-policy-framework-addon-acm-217,
      acm-cli-acm-217, cert-policy-controller-acm-217, multicluster-operators-subscription-acm-217,
      submariner-addon-acm-217, search-indexer-acm-217, mtv-integrations-acm-217,
      multicloud-integrations-acm-217, multicluster-operators-channel-acm-217, governance-policy-propagator-acm-217,
      insights-client-acm-217, search-collector-acm-217, search-v2-operator-acm-217,
      multicluster-operators-application-acm-217, governance-policy-addon-controller-acm-217,
      insights-metrics-acm-217' is(are) not included in snapshot due to missing valid
      containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-217-release-acm-217-20260216-010151-000":{"lastUpdateTime":"2026-02-16T01:12:39.429809203Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1771203711000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/siteconfig
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-217","status":"TestPassed","lastUpdateTime":"2026-02-16T01:12:39.429809203Z","details":"Integration
      test passed","startTime":"2026-02-16T01:11:57.460958354Z","completionTime":"2026-02-16T01:12:39.429809203Z","testPipelineRunName":"enterprise-contract-acm-217-6jqkh"}]'
  creationTimestamp: "2026-02-16T01:11:57Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-217
    appstudio.openshift.io/build-pipelinerun: siteconfig-acm-217-on-push-cgfdr
    appstudio.openshift.io/component: siteconfig-acm-217
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "63696550078"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: siteconfig-acm-217-on-push
    pac.test.appstudio.openshift.io/pull-request: "891"
    pac.test.appstudio.openshift.io/repository: siteconfig-main
    pac.test.appstudio.openshift.io/sha: c78923c118ecb8f169537c9ce14a13cef3eae517
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: siteconfig
    test.appstudio.openshift.io/pipelinerunfinishtime: "1771204312"
    test.appstudio.openshift.io/type: component
  name: release-acm-217-20260216-010151-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-217
    uid: f6a47cb4-5edb-49df-b280-ca2ad71f1d6c
  resourceVersion: "7297814769"
  uid: 6ef520e2-124f-4bb8-a272-ff1a687396d4
spec:
  application: release-acm-217
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-config-reloader-acm-217@sha256:fb091bc3810b308da92453ffbba89ad1d3947de3e8435b2977b44528dbd9899e
    name: prometheus-config-reloader-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: cmd/prometheus-config-reloader/Containerfile.operator
        revision: 9668cecb5f082ebc431cd518c9a1c5a4a327d2fd
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/thanos-receive-controller-acm-217@sha256:472b6edf5c1a3becf467786edea1eaba38bd2998f2a6427835cbddca068101fc
    name: thanos-receive-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 544e6a9dca32f4e99e6bb6224abb70c3810aec3f
        url: https://github.com/stolostron/thanos-receive-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/thanos-acm-217@sha256:eeb0eb2cb9a8d658bea19b14c00b42321bcfcd44f87e302f48f79afdf0a6e0fe
    name: thanos-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: b5e6db80e2389b8e064cb9ca6dbff9cefc7481a2
        url: https://github.com/stolostron/thanos
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-state-metrics-acm-217@sha256:f1e61e2ab74840a79a238e850115dc7baa3513487206e5f6702d1f783f4a7ef3
    name: kube-state-metrics-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: f6d50f1813db9bb19158387e181bc940d91081b8
        url: https://github.com/stolostron/kube-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/memcached-exporter-acm-217@sha256:6d8a4830f1032dd01ae3d863fa954a632a4ee6abc5cde01bf764efd380ffe78b
    name: memcached-exporter-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 79b120f05bb178e84e6cda7be504844c37224438
        url: https://github.com/stolostron/memcached_exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-217@sha256:05c4e466627234838eee27f0e63ef707b0390dcf3a55d32418e66bad88f96bef
    name: siteconfig-acm-217
    source:
      git:
        revision: c78923c118ecb8f169537c9ce14a13cef3eae517
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-acm-217@sha256:82970b53a13fd6023bea32f866e4f3b2359fa917b27c65f832736da4b894fb22
    name: kube-rbac-proxy-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 29aba2f0e273d5ff2602c3690a8bff2ed55f40d3
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-acm-217@sha256:25106c6464b9de02ccfc25fea729f63aff293b5deb48d25cca4926a313931972
    name: prometheus-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 1cb211b8aa72d2452271c174cec2ce735d24689f
        url: https://github.com/stolostron/prometheus
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/obo-prometheus-operator-acm-217@sha256:9c0d4745ea8a632830812b4da0875f13a7d17ccbd50825a33c067c1a7e9d5d32
    name: obo-prometheus-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.prom-operator
        revision: 28a438c59f3fdfec3625f573aa484d0bbe8e7373
        url: https://github.com/stolostron/obo-prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/grafana-acm-217@sha256:6dba8d81259706958b3d81ce45f55318f16add240aaebf15dcce5eac72b64cec
    name: grafana-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 986aa31b00d5d691ec6d4ea7725ff41e38e479bb
        url: https://github.com/stolostron/grafana
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-observability-addon-acm-217@sha256:da43e78debb6e7f63f87fc56e7a0f33f710afd9235631a593bcd5bdf56085683
    name: multicluster-observability-addon-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 595254d30bc3bec01a5e7e2ceb096717914afc6a
        url: https://github.com/stolostron/multicluster-observability-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/node-exporter-acm-217@sha256:2beb2ea411a6add7af4d2355244b8cf804d4c7a1a94e9ee5b13a9060d8e9368a
    name: node-exporter-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 370b9e83e278f56f52324badb5d9fbb67e8d947d
        url: https://github.com/stolostron/node-exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-operator-acm-217@sha256:3a7641c9c2ae8424637580ade6b4c8cc695713f590ba97edfe751bf623c7375d
    name: prometheus-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9668cecb5f082ebc431cd518c9a1c5a4a327d2fd
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/rbac-query-proxy-acm-217@sha256:9eff0c187f005a80725f6b02a1a4e72e7cc6f39593b25f873857a41b2f2b6306
    name: rbac-query-proxy-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: proxy/Containerfile.operator
        revision: 0ce5434a02708da0d4bd35da488e785f688c76c6
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-217@sha256:62612f2ef6867dcb0b1e756f45c80fdee03c701ece60ee9587da715909f190e3
    name: console-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: d46fadadee4836b15e5bba376278a2492518cca7
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-217@sha256:335900bab1a31f35bc3f83318ef0f52b1bfed4e8ae03a45792b99e441efcd450
    name: klusterlet-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 351170246988c898578145f9823f5bed981d5823
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/metrics-collector-acm-217@sha256:608e1fcfec17544dbf954bb698b1888c78873ae8dd4d6e9709655aa64807a1bc
    name: metrics-collector-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: collectors/metrics/Containerfile.operator
        revision: 0ce5434a02708da0d4bd35da488e785f688c76c6
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-operator-acm-217@sha256:5264e0c5f0b8a0f86cc8dc4269f01c2ac4f25f97b4cdb24209e23193ff01bf5d
    name: observatorium-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: f35faa5c3e7034aa50276de3fffaaf0e0a684831
        url: https://github.com/stolostron/observatorium-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-acm-217@sha256:c285a50e1ad22cfb35811da17918b43371a6e6185c4432838c73499d8adfcd35
    name: observatorium-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 3a9700185013ca69fc2dc02e7b55e4dcbc4d766d
        url: https://github.com/stolostron/observatorium
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-observability-operator-acm-217@sha256:e03c411ee74a80cd5b4e1bd7e365dd1e09381228a3f2a70a07a279fc2a64e13b
    name: multicluster-observability-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: operators/multiclusterobservability/Containerfile.operator
        revision: 0ce5434a02708da0d4bd35da488e785f688c76c6
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-217@sha256:dad2944b730b90b0ee0a5cd0cd5e4aba621a1eeeb3e3fa13612ce52ae0a8a2ff
    name: multiclusterhub-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: ac9fdc5fe976d981cd243d8c220dfc840dfa8693
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-alertmanager-acm-217@sha256:4a163d5df25b4d40b0f50bca7fe53982d0a4b9938ffc644aff5874fce3a88f47
    name: prometheus-alertmanager-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: de4e0df581cc11480b71ad87bc6cb5865aedf057
        url: https://github.com/stolostron/prometheus-alertmanager
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-217@sha256:4f5b2dae71558fc4290667f83de6a9976572f6c4919b9c84c5ac06eaf00a9ac9
    name: volsync-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 304c9b5d9f6705ae9d881b31dc9cd369a4d87556
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-217@sha256:6777e3ec77a834d59e81284dee22c88fcaa8d897628ba8ec368a6e07a48a0655
    name: cluster-backup-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1b2e5610c254f2d724aa80039b31cd2cf8f03d45
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/endpoint-monitoring-operator-acm-217@sha256:d2089f72e106ab0b8b76f787f73e314f77e0fe2909d97db7065edbdb6f0cf1d7
    name: endpoint-monitoring-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: operators/endpointmetrics/Containerfile.operator
        revision: 0ce5434a02708da0d4bd35da488e785f688c76c6
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/grafana-dashboard-loader-acm-217@sha256:eb13a883a893c520c628c5a7184d6f149f5eddb15e24712033327b3dabe6efd2
    name: grafana-dashboard-loader-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: loaders/dashboards/Containerfile.operator
        revision: 0ce5434a02708da0d4bd35da488e785f688c76c6
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-217@sha256:97e1b298aac477a3f1e031c1f1223072b9432300ecf745fcec7356a2fb4db096
    name: multicluster-role-assignment-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 219981e942f32ac447802aeae4d1d86eb8bbf90e
        url: https://github.com/stolostron/multicluster-role-assignment
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-permission-acm-217@sha256:ff7e85e5323ac74eedf0c71c584a76641e055d5430fcd9c72fe3129b92cf204d
    name: cluster-permission-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 25f12b79a1fd44c502e1e9757ba4d82994be6518
        url: https://github.com/stolostron/cluster-permission
status:
  conditions:
  - lastTransitionTime: "2026-02-16T01:12:39Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-16T01:12:39Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-16T01:12:39Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
