apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/volsync-addon-controller?rev=ceea500ec650cdd35637b3c23deaf39aa1610176
    build.appstudio.redhat.com/commit_sha: ceea500ec650cdd35637b3c23deaf39aa1610176
    build.appstudio.redhat.com/target_branch: release-2.17
    pac.test.appstudio.openshift.io/branch: release-2.17
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "63018329107"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-juavzl
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/volsync-addon-controller-acm-217-on-push-sj8zw
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.17"
    pac.test.appstudio.openshift.io/original-prname: volsync-addon-controller-acm-217-on-push
    pac.test.appstudio.openshift.io/pull-request: "1265"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/volsync-addon-controller
    pac.test.appstudio.openshift.io/repository: volsync-addon-controller-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: ceea500ec650cdd35637b3c23deaf39aa1610176
    pac.test.appstudio.openshift.io/sha-title: |-
      automatic update in main of VolSync release-0.15 helm charts (#1265)

      Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/volsync-addon-controller/commit/ceea500ec650cdd35637b3c23deaf39aa1610176
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.17
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/volsync-addon-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: volsync-addon-controller
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-09T20:34:12Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'metrics-collector-acm-217,
      mtv-integrations-acm-217, multicloud-integrations-acm-217, multicluster-operators-channel-acm-217,
      observatorium-operator-acm-217, observatorium-acm-217, governance-policy-propagator-acm-217,
      insights-client-acm-217, multicluster-observability-operator-acm-217, multiclusterhub-operator-acm-217,
      prometheus-alertmanager-acm-217, search-collector-acm-217, search-v2-operator-acm-217,
      endpoint-monitoring-operator-acm-217, grafana-dashboard-loader-acm-217, multicluster-operators-application-acm-217,
      multicluster-role-assignment-acm-217, governance-policy-addon-controller-acm-217,
      insights-metrics-acm-217, search-v2-api-acm-217, config-policy-controller-acm-217,
      must-gather-acm-217, prometheus-config-reloader-acm-217, thanos-receive-controller-acm-217,
      thanos-acm-217, governance-policy-framework-addon-acm-217, kube-state-metrics-acm-217,
      memcached-exporter-acm-217, siteconfig-acm-217, acm-cli-acm-217, cert-policy-controller-acm-217,
      kube-rbac-proxy-acm-217, multicluster-operators-subscription-acm-217, prometheus-acm-217,
      submariner-addon-acm-217, obo-prometheus-operator-acm-217, grafana-acm-217,
      multicluster-observability-addon-acm-217, node-exporter-acm-217, prometheus-operator-acm-217,
      rbac-query-proxy-acm-217, search-indexer-acm-217, console-acm-217' is(are) not
      included in snapshot due to missing valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-217-release-acm-217-20260209-201925-000":{"lastUpdateTime":"2026-02-09T20:34:52.252476839Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1770668365000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/volsync-addon-controller
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-217","status":"TestPassed","lastUpdateTime":"2026-02-09T20:34:52.252476839Z","details":"Integration
      test passed","startTime":"2026-02-09T20:34:12.424276705Z","completionTime":"2026-02-09T20:34:52.252476839Z","testPipelineRunName":"enterprise-contract-acm-217-2k4dr"}]'
  creationTimestamp: "2026-02-09T20:34:12Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-217
    appstudio.openshift.io/build-pipelinerun: volsync-addon-controller-acm-217-on-push-sj8zw
    appstudio.openshift.io/component: volsync-addon-controller-acm-217
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "63018329107"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: volsync-addon-controller-acm-217-on-push
    pac.test.appstudio.openshift.io/pull-request: "1265"
    pac.test.appstudio.openshift.io/repository: volsync-addon-controller-acm-210
    pac.test.appstudio.openshift.io/sha: ceea500ec650cdd35637b3c23deaf39aa1610176
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: volsync-addon-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1770669246"
    test.appstudio.openshift.io/type: component
  name: release-acm-217-20260209-201925-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-217
    uid: f6a47cb4-5edb-49df-b280-ca2ad71f1d6c
  resourceVersion: "7174239507"
  uid: 9e49d700-e3e0-4299-abaa-9744a75222d5
spec:
  application: release-acm-217
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-217@sha256:335900bab1a31f35bc3f83318ef0f52b1bfed4e8ae03a45792b99e441efcd450
    name: klusterlet-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 351170246988c898578145f9823f5bed981d5823
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-217@sha256:c61a7c2e831052c4ad2af0ad12273aa1cbd3ed4953297c724e52fc0eca00ef5d
    name: volsync-addon-controller-acm-217
    source:
      git:
        revision: ceea500ec650cdd35637b3c23deaf39aa1610176
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-217@sha256:d97d6e9892c55a3978b10532582218c67c3c1f6f1f98f36f77a8bb563b063402
    name: cluster-backup-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4366fe7a8095aa3dc63db5f18a0ff151d57f71c8
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-permission-acm-217@sha256:ff7e85e5323ac74eedf0c71c584a76641e055d5430fcd9c72fe3129b92cf204d
    name: cluster-permission-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 25f12b79a1fd44c502e1e9757ba4d82994be6518
        url: https://github.com/stolostron/cluster-permission
status:
  conditions:
  - lastTransitionTime: "2026-02-09T20:34:52Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-09T20:34:52Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-09T20:34:54Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
