apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/prometheus-operator?rev=5f8ace5fa4a9cf869f191cdacd5e8859d07d9cf8
    build.appstudio.redhat.com/commit_sha: 5f8ace5fa4a9cf869f191cdacd5e8859d07d9cf8
    build.appstudio.redhat.com/target_branch: release-2.16
    pac.test.appstudio.openshift.io/branch: release-2.16
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "55201857467"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-crfoce
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/prometheus-operator-acm-216-on-push-jjwh4
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.16"
    pac.test.appstudio.openshift.io/original-prname: prometheus-operator-acm-216-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/prometheus-operator
    pac.test.appstudio.openshift.io/repository: prometheus-config-reloader-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: jacobbaungard
    pac.test.appstudio.openshift.io/sha: 5f8ace5fa4a9cf869f191cdacd5e8859d07d9cf8
    pac.test.appstudio.openshift.io/sha-title: Migrate konflux files to 2.16
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/prometheus-operator/commit/5f8ace5fa4a9cf869f191cdacd5e8859d07d9cf8
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.16
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/prometheus-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: prometheus-operator
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-11-12T15:57:22Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'multicluster-operators-channel-acm-216,
      cluster-permission-acm-216, memcached-exporter-acm-216, multicluster-operators-subscription-acm-216,
      governance-policy-framework-addon-acm-216, kube-state-metrics-acm-216, multicluster-operators-application-acm-216,
      prometheus-config-reloader-acm-216, kube-rbac-proxy-acm-216, submariner-addon-acm-216,
      grafana-acm-216, thanos-acm-216, endpoint-monitoring-operator-acm-216, multicluster-observability-addon-acm-216'
      is(are) not included in snapshot due to missing valid containerImage or git
      source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-216-release-acm-216-x84s2":{"lastUpdateTime":"2025-11-12T15:57:59.993673904Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762961626"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/prometheus-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-216","status":"TestPassed","lastUpdateTime":"2025-11-12T15:57:59.993673904Z","details":"Integration
      test passed","startTime":"2025-11-12T15:57:23.387339206Z","completionTime":"2025-11-12T15:57:59.993673904Z","testPipelineRunName":"enterprise-contract-acm-216-9xjdh"}]'
  creationTimestamp: "2025-11-12T15:57:22Z"
  generateName: release-acm-216-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-216
    appstudio.openshift.io/build-pipelinerun: prometheus-operator-acm-216-on-push-jjwh4
    appstudio.openshift.io/component: prometheus-operator-acm-216
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "55201857467"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: prometheus-operator-acm-216-on-push
    pac.test.appstudio.openshift.io/repository: prometheus-config-reloader-acm-210
    pac.test.appstudio.openshift.io/sha: 5f8ace5fa4a9cf869f191cdacd5e8859d07d9cf8
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: prometheus-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762963034"
    test.appstudio.openshift.io/type: component
  name: release-acm-216-x84s2
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-216
    uid: 36e17c1d-3fe4-44ec-96e0-7fac572eda72
  resourceVersion: "5815995360"
  uid: dcf6d7e6-53fa-4a47-9fc1-a80a0c00a907
spec:
  application: release-acm-216
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/must-gather-acm-216@sha256:c443aff1c5edb73cbf2e775b9b075186b118411cd199f7ab5c20f5c588c55e82
    name: must-gather-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 4774a53376e3583ab2364142ccda378f26a048ed
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-216@sha256:7909a5eb9194bb4c5c5f8b2a97852174e097f10e17d5455ca516695ec3d68616
    name: search-collector-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 95972870f9caa2b81b49558c7d8ec523b5e4703b
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/thanos-receive-controller-acm-216@sha256:f77a2699315ef5a3f053b1aa4033a758be1167b4765adb7722d73360db9e1bf8
    name: thanos-receive-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: bf6a7d16dfd9e36cc8047071989ee2879fffbb43
        url: https://github.com/stolostron/thanos-receive-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-216@sha256:2b6f1e57833aa98d7e0acec558b1da44138b1eed22185bb4459d41463f1cb193
    name: insights-client-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c5a46b852fdcf8d875379289637fa1d93fabb844
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-operator-acm-216@sha256:211183c4ff231f77433a8161a5712cf8c13b7cf60abf9100be6c6c2026e6c631
    name: observatorium-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 3c2e8d7c53464da2003790df1b3d17674c99dd66
        url: https://github.com/stolostron/observatorium-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-216@sha256:f616cebe5b21ffb21443b5edf7abf89ce30de65c7f8cb203cb5f4967a47e148f
    name: volsync-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 96320c2b571c829fb626baafa030ae52c7f1b136
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-216@sha256:8bf97058b7c29c029cc92e568709300da53afc4964a1de5ff3aa34f8d92220bd
    name: console-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 78e841cd540f8049892a24cfe91d14e04fce2a4f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/grafana-dashboard-loader-acm-216@sha256:303ed3b47a0c0ffb23623bbeb17f85e2701ef7e24c1a6138ea525804a8690be3
    name: grafana-dashboard-loader-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: loaders/dashboards/Containerfile.operator
        revision: d9079fb0274d5e6d7c402f19956bea73d16e0eaa
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-216@sha256:ec786c372f0fc592c2484e10fe952732b008fe423ed6159ee159e2c1faf9f8ac
    name: search-indexer-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: be3464b54648070954457daa16d82d963a3d69ea
        url: https://github.com/stolostron/search-indexer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-216@sha256:b0bca20324584e8b9fd4c6bbebb972f46e8ed8caf99850d91469ae3b09c789f0
    name: siteconfig-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 5c7948458a83dd750efc7c73eb995dc2d16d1a6f
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-216@sha256:3cb36c91e01c9977500c8d3ef5c403c87e3eee73380a6727912b07f52f8342c2
    name: cluster-backup-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8cec7602693bd1e44b85b024ba3d01c492aebaf6
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-alertmanager-acm-216@sha256:eae2d05de0e4c62e56b3f069ec9711a3064c58306599326ed8721ccce9aacc82
    name: prometheus-alertmanager-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 39c7d57abb61d551dd6318931a85831748775401
        url: https://github.com/stolostron/prometheus-alertmanager
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-operator-acm-216@sha256:8787643315a9b349ada472e67d3f1b0e8f2bc3f0605f89303da2b66d3b2865fe
    name: prometheus-operator-acm-216
    source:
      git:
        revision: 5f8ace5fa4a9cf869f191cdacd5e8859d07d9cf8
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/acm-cli-acm-216@sha256:3dc11a8646062e23611ed9f83d9490d43f12133c1b95a289a9855ee52f0d783e
    name: acm-cli-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f3e05e5fd1af46f9ca3b03c3a9f6ffebfbff30ae
        url: https://github.com/stolostron/acm-cli
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-propagator-acm-216@sha256:dedef313931717845ef42a0c45d1caf338032fbe6f7e112cd1a88099ee53d877
    name: governance-policy-propagator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2c502c2c859c21bc649a9ee9335bc961197c9a1c
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-216@sha256:506aa32aa43b96f6eb83003228d5facd82a2bb69e013800a39af6611b326a99f
    name: klusterlet-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 31d78023b7f23d35f82eef5f0cb8c58a9e32cc2c
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-216@sha256:9df7d0fbc2ca862ec746b6e315c7f05e7a14e094e5273386c474af9b32412317
    name: multicloud-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 201f0868adf6680655d73338c730a7dedbd37324
        url: https://github.com/stolostron/multicloud-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/rbac-query-proxy-acm-216@sha256:5c66c014032c2d090babca028b9e11cd7e035e8ed7f1ea0da9a4918919fe49b4
    name: rbac-query-proxy-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: proxy/Containerfile.operator
        revision: d9079fb0274d5e6d7c402f19956bea73d16e0eaa
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-216@sha256:277e2546dd5523114a060625447aba92c52c5906c77699a7f8f14b23465e51f9
    name: search-v2-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c67352e80db2c462de883f0484a3c8d550fdbb90
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cert-policy-controller-acm-216@sha256:df6c5854fe6ae32ef2cb06806d57e0da6dbdb4807093edff7a299ebddab675b8
    name: cert-policy-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: e51cc33724db8bb88b37d063225ef649855ca304
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller-acm-216@sha256:d715dca420bdae96cf1c8de026888d799ea383648fbca844c0ae8d0b3b866250
    name: config-policy-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7be13b63c3435e913c61004002041f3586ae0816
        url: https://github.com/stolostron/config-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller-acm-216@sha256:0c33e79fad37fb24ae5f0d250ee4d169c4cddfbb9c28dac532a4fc76362b7471
    name: governance-policy-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2b3cb20c875d3c485751281b870bbe251665326b
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-216@sha256:36f536aeb1506b2149651dd68ed06846a8fdecfa1f5c8440ba887fa0ec192642
    name: insights-metrics-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3260e625b844d64fde64747d65a596d3c9d9cd57
        url: https://github.com/stolostron/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/metrics-collector-acm-216@sha256:3034ec52fbc45247c29fa0ce41b022169a7db98db9bf5ed8ce7e5bdf432523de
    name: metrics-collector-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: collectors/metrics/Containerfile.operator
        revision: d9079fb0274d5e6d7c402f19956bea73d16e0eaa
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-216@sha256:51c7b635493894ffb36090ba4ec0fd35c294b39740b0fc5d93f127aa0d7a6ce3
    name: mtv-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 513a1ecbaf4063e4c0d643f7d7b231cb162df3f1
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-observability-operator-acm-216@sha256:c9f6975f3496cdaa521236e08efb135c17cfa6198b13442b18a1b084079f6609
    name: multicluster-observability-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: operators/multiclusterobservability/Containerfile.operator
        revision: d9079fb0274d5e6d7c402f19956bea73d16e0eaa
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-216@sha256:8e10b2842bd1e533c78254d526cb6485646d6f08d6930ad8dce0419a9ed3cc11
    name: multicluster-role-assignment-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 57c73e9263314c329e4c81b04e8bab4951c019ab
        url: https://github.com/stolostron/multicluster-role-assignment
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-216@sha256:460330c8c3e06206f6f15dc2def3f9341adf63720232845fd07fea8e83c2b320
    name: multiclusterhub-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: afad8efdb58a04ab304977e27cefd3268f2c3b78
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/node-exporter-acm-216@sha256:326dcf4f76e349e1ae77fa0bd97dc17ef8c978cb17bd827771a24223995caf0a
    name: node-exporter-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: fa808a033fcd7f3e21a9787ba1162184a36815a1
        url: https://github.com/stolostron/node-exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-acm-216@sha256:507e11d76a1be9082fd5e4c3e32b2dc4f822b9ac09f5c1ca47a88aec566aa37c
    name: observatorium-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 7566829068b83ec083e3fd7e2c0dde2cd5330b70
        url: https://github.com/stolostron/observatorium
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-acm-216@sha256:c6bd518f68769d771ab7beabf4609ecf13b7cdf67046dca8206464bbbe8beaf1
    name: prometheus-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: c43e7802eff2f71b318a2ac6e6f6955684b37d6d
        url: https://github.com/stolostron/prometheus
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-216@sha256:8083f59328e29d240b5af1d50dbe26cb00c30aa4ed57706fe34e7631b1b13c19
    name: search-v2-api-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 741ef9d24b4a7c7eabd2ae62269a9f718b824e25
        url: https://github.com/stolostron/search-v2-api
status:
  conditions:
  - lastTransitionTime: "2025-11-12T15:58:00Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-12T15:58:00Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-12T15:58:00Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
