apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicluster-role-assignment?rev=219981e942f32ac447802aeae4d1d86eb8bbf90e
    build.appstudio.redhat.com/commit_sha: 219981e942f32ac447802aeae4d1d86eb8bbf90e
    build.appstudio.redhat.com/target_branch: release-2.17
    pac.test.appstudio.openshift.io/branch: release-2.17
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "63455092721"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-rjgjnr
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/multicluster-role-assignment-acm-217-on-push-scrp9
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.17"
    pac.test.appstudio.openshift.io/original-prname: multicluster-role-assignment-acm-217-on-push
    pac.test.appstudio.openshift.io/pull-request: "250"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicluster-role-assignment
    pac.test.appstudio.openshift.io/repository: multicluster-role-assignment-acm-215
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 219981e942f32ac447802aeae4d1d86eb8bbf90e
    pac.test.appstudio.openshift.io/sha-title: |-
      Red Hat Konflux update multicluster-role-assignment-acm-217 (#250)

      * Red Hat Konflux update multicluster-role-assignment-acm-217

      Signed-off-by: red-hat-konflux <konflux@no-reply.konflux-ci.dev>

      * Removed cel expression comments

      Signed-off-by: Matthew Short <mshort@redhat.com>

      * Renamed/updated 216 tekton files for 217

      Signed-off-by: Matthew Short <mshort@redhat.com>

      * Enhanced cel expression a bit in 217 pr file

      Signed-off-by: Matthew Short <mshort@redhat.com>

      * Added claude command for updating tekton files

      Signed-off-by: Matthew Short <mshort@redhat.com>

      ---------

      Signed-off-by: red-hat-konflux <konflux@no-reply.konflux-ci.dev>
      Signed-off-by: Matthew Short <mshort@redhat.com>
      Co-authored-by: red-hat-konflux <konflux@no-reply.konflux-ci.dev>
      Co-authored-by: Matthew Short <mshort@redhat.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicluster-role-assignment/commit/219981e942f32ac447802aeae4d1d86eb8bbf90e
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.17
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicluster-role-assignment
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicluster-role-assignment
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-12T22:08:22Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'governance-policy-addon-controller-acm-217,
      insights-metrics-acm-217, search-v2-api-acm-217, config-policy-controller-acm-217,
      must-gather-acm-217, prometheus-config-reloader-acm-217, thanos-receive-controller-acm-217,
      thanos-acm-217, governance-policy-framework-addon-acm-217, kube-state-metrics-acm-217,
      memcached-exporter-acm-217, siteconfig-acm-217, acm-cli-acm-217, cert-policy-controller-acm-217,
      kube-rbac-proxy-acm-217, multicluster-operators-subscription-acm-217, prometheus-acm-217,
      submariner-addon-acm-217, obo-prometheus-operator-acm-217, grafana-acm-217,
      multicluster-observability-addon-acm-217, node-exporter-acm-217, prometheus-operator-acm-217,
      rbac-query-proxy-acm-217, search-indexer-acm-217, metrics-collector-acm-217,
      mtv-integrations-acm-217, multicloud-integrations-acm-217, multicluster-operators-channel-acm-217,
      observatorium-operator-acm-217, observatorium-acm-217, governance-policy-propagator-acm-217,
      insights-client-acm-217, multicluster-observability-operator-acm-217, prometheus-alertmanager-acm-217,
      search-collector-acm-217, search-v2-operator-acm-217, endpoint-monitoring-operator-acm-217,
      grafana-dashboard-loader-acm-217, multicluster-operators-application-acm-217'
      is(are) not included in snapshot due to missing valid containerImage or git
      source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-217-release-acm-217-20260212-215613-000":{"lastUpdateTime":"2026-02-12T22:08:57.281099623Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1770933373000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicluster-role-assignment
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-217","status":"TestPassed","lastUpdateTime":"2026-02-12T22:08:57.281099623Z","details":"Integration
      test passed","startTime":"2026-02-12T22:08:22.700152216Z","completionTime":"2026-02-12T22:08:57.281099623Z","testPipelineRunName":"enterprise-contract-acm-217-4wxvw"}]'
  creationTimestamp: "2026-02-12T22:08:22Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-217
    appstudio.openshift.io/build-pipelinerun: multicluster-role-assignment-acm-217-on-push-scrp9
    appstudio.openshift.io/component: multicluster-role-assignment-acm-217
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "63455092721"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multicluster-role-assignment-acm-217-on-push
    pac.test.appstudio.openshift.io/pull-request: "250"
    pac.test.appstudio.openshift.io/repository: multicluster-role-assignment-acm-215
    pac.test.appstudio.openshift.io/sha: 219981e942f32ac447802aeae4d1d86eb8bbf90e
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicluster-role-assignment
    test.appstudio.openshift.io/pipelinerunfinishtime: "1770934096"
    test.appstudio.openshift.io/type: component
  name: release-acm-217-20260212-215613-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-217
    uid: f6a47cb4-5edb-49df-b280-ca2ad71f1d6c
  resourceVersion: "7247343473"
  uid: 95fa4a33-1871-4618-aadf-baea6f8729bf
spec:
  application: release-acm-217
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-permission-acm-217@sha256:ff7e85e5323ac74eedf0c71c584a76641e055d5430fcd9c72fe3129b92cf204d
    name: cluster-permission-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 25f12b79a1fd44c502e1e9757ba4d82994be6518
        url: https://github.com/stolostron/cluster-permission
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-217@sha256:35022e588448a48d3909a1cbe96617e7ede1aabd1f076507333db08543845646
    name: console-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 7362b7649772d9ceb6df1f9d8b59c574b213d2b7
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-217@sha256:335900bab1a31f35bc3f83318ef0f52b1bfed4e8ae03a45792b99e441efcd450
    name: klusterlet-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 351170246988c898578145f9823f5bed981d5823
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-217@sha256:dad2944b730b90b0ee0a5cd0cd5e4aba621a1eeeb3e3fa13612ce52ae0a8a2ff
    name: multiclusterhub-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: ac9fdc5fe976d981cd243d8c220dfc840dfa8693
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-217@sha256:4f5b2dae71558fc4290667f83de6a9976572f6c4919b9c84c5ac06eaf00a9ac9
    name: volsync-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 304c9b5d9f6705ae9d881b31dc9cd369a4d87556
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-217@sha256:6777e3ec77a834d59e81284dee22c88fcaa8d897628ba8ec368a6e07a48a0655
    name: cluster-backup-operator-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1b2e5610c254f2d724aa80039b31cd2cf8f03d45
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-role-assignment-acm-217@sha256:97e1b298aac477a3f1e031c1f1223072b9432300ecf745fcec7356a2fb4db096
    name: multicluster-role-assignment-acm-217
    source:
      git:
        revision: 219981e942f32ac447802aeae4d1d86eb8bbf90e
        url: https://github.com/stolostron/multicluster-role-assignment
status:
  conditions:
  - lastTransitionTime: "2026-02-12T22:08:57Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-12T22:08:57Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-12T22:08:57Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
