apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/console?rev=834f26274141c4bbda9df9f76f34d5c7d73d020a
    build.appstudio.redhat.com/commit_sha: 834f26274141c4bbda9df9f76f34d5c7d73d020a
    build.appstudio.redhat.com/target_branch: release-2.12
    pac.test.appstudio.openshift.io/branch: release-2.12
    pac.test.appstudio.openshift.io/check-run-id: "30335554538"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-mgnsma
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://console.redhat.com/application-pipeline/ns/crt-redhat-acm-tenant/pipelinerun/console-acm-212-on-push-jjfxk
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.12"
    pac.test.appstudio.openshift.io/original-prname: console-acm-212-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/console
    pac.test.appstudio.openshift.io/repository: console
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 834f26274141c4bbda9df9f76f34d5c7d73d020a
    pac.test.appstudio.openshift.io/sha-title: fix exception in overviewDataFunctions
      (#3876)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/console/commit/834f26274141c4bbda9df9f76f34d5c7d73d020a
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.12
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/console
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: console
    test.appstudio.openshift.io/pipelinerunstarttime: "1726684202"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/console
  creationTimestamp: "2024-09-18T18:46:24Z"
  generateName: release-acm-212-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-212
    appstudio.openshift.io/build-pipelinerun: console-acm-212-on-push-jjfxk
    appstudio.openshift.io/component: console-acm-212
    pac.test.appstudio.openshift.io/check-run-id: "30335554538"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: console-acm-212-on-push
    pac.test.appstudio.openshift.io/repository: console
    pac.test.appstudio.openshift.io/sha: 834f26274141c4bbda9df9f76f34d5c7d73d020a
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: console
    test.appstudio.openshift.io/pipelinerunfinishtime: "1726685176"
    test.appstudio.openshift.io/type: component
  name: release-acm-212-zc2vq
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-212
    uid: 7db15465-421e-4351-8cb5-a86758aad006
  resourceVersion: "2313720008"
  uid: aa1fcae5-62cf-4509-9cc2-bdf8182b0e14
spec:
  application: release-acm-212
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/observatorium-acm-212@sha256:398fe6c75321f9a7fb7e13bf047701176733698feaac575683d10d556986099a
    name: observatorium-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: d18c0c43bed61744b2dd05d324d6cde66271fae1
        url: https://github.com/stolostron/observatorium
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/observatorium-operator-acm-212@sha256:54d5593824273facd2316759ea7fe5df41071010c74ae47421d2c3abef0ee2b3
    name: observatorium-operator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: ef6237565831ae7f876367ddaf3388da276c5ee2
        url: https://github.com/stolostron/observatorium-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/rbac-query-proxy-acm-212@sha256:030c55b610f45f7a12cdf4e8a2ba31dac6ead27537ecf80cc9efd56273ef79b1
    name: rbac-query-proxy-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: proxy/Containerfile.operator
        revision: 6f12d6be872e2c052926db05eb1ebe304c5a1d78
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/cluster-backup-operator-acm-212@sha256:5380a184daec98170bc59d4f211c6880dc1c8c5021834080392b89ce3bd1fb4f
    name: cluster-backup-operator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 13d4b0dcae53d83c745e113fd16b84cada952e51
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/endpoint-monitoring-operator-acm-212@sha256:4e68f9d597d11ca00457725bae582636abfaa26421c810cd808fd95ab7904e71
    name: endpoint-monitoring-operator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: operators/endpointmetrics/Containerfile.operator
        revision: 6f12d6be872e2c052926db05eb1ebe304c5a1d78
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/node-exporter-acm-212@sha256:60806e4aeaaacda3a6219a5184be62f23212389a4dfd9b93d29211d4856992a6
    name: node-exporter-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: db8127e87e2f72c6b4b500e152d015d61b8f2b6c
        url: https://github.com/stolostron/node-exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/console-acm-212@sha256:a57395e423be8cd5f124577c0e107032218c53c99d74af24358f66639a8d53c9
    name: console-acm-212
    source:
      git:
        revision: 834f26274141c4bbda9df9f76f34d5c7d73d020a
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/grafana-acm-212@sha256:d8ad741d77809249b398bd48496c3fef04cb290638995d597ebabedddddcd8c2
    name: grafana-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 999dd5e48a8b80406c068db34ba7da0620c592d4
        url: https://github.com/stolostron/grafana
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/must-gather-acm-212@sha256:4a9c0494602a8dc127a19b2950f8a64077638dd548ae6dbb910ba0a64c8f9ce7
    name: must-gather-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 0a041945944fe29003f10406ad9b2a21ad8fb83a
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/multicluster-observability-operator-acm-212@sha256:33795624813cd0b174dbdc8087184de5e2b711cd5864b61602735278ecf7fe8f
    name: multicluster-observability-operator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: operators/multiclusterobservability/Containerfile.operator
        revision: 6f12d6be872e2c052926db05eb1ebe304c5a1d78
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/thanos-acm-212@sha256:bf1429dcdf742bbaaefda3808d3189fde7a23f5e7f8128a235fae6ea24b8226a
    name: thanos-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: a71bab0574d82a4d52f84df2690704ec3955baef
        url: https://github.com/stolostron/thanos
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/prometheus-operator-acm-212@sha256:c833bd2ae45145378977095701b4b6e1e233f92c5c80478432a981465a9a7340
    name: prometheus-operator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 233733b1cb030fdd82da736940e9e6a1e1bf5d91
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/siteconfig-acm-212@sha256:85e286c5585584bf52fa653bd1f0680fce89e4e1468a1baf6d7b544b197fd162
    name: siteconfig-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 69897b2a21b19d508b73a24a40cb17ed5fb2e07f
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/governance-policy-addon-controller-acm-212@sha256:db212f09800e1a1ef26cd236efd1092206ca1c36f5bd31579c95f43cfa7d1bc5
    name: governance-policy-addon-controller-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 83c43c4f9f8a436c6d4f0715f9d944a80d6e4335
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/prometheus-alertmanager-acm-212@sha256:6609e60b7f5eaee82b3bcccd53f1cf51a87c6ca1d74abef8c7824eb969377ea2
    name: prometheus-alertmanager-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: c060ead63526db262c25712a87259ca4438732ba
        url: https://github.com/stolostron/prometheus-alertmanager
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/kube-state-metrics-acm-212@sha256:e65dc2081a8535989b287c442836c39798b942d93d659f930b3e4dcbf783d40f
    name: kube-state-metrics-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 987eebabcaddb9c528ce4f6417a71c2659c7cb4c
        url: https://github.com/stolostron/kube-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/cert-policy-controller-acm-212@sha256:7863144e3062fa853e64f18e0078bc7f3501dad6a223aba40f4f58b1d708d081
    name: cert-policy-controller-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: dcdb04db00df2e16825dcb567b1c7aab258e417d
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/governance-policy-propagator-acm-212@sha256:4e922e3a216e2578921c175f12c7c5d738a56221588d5caac1395f36863bff9b
    name: governance-policy-propagator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 74fff120495651905d82f185a86cf0f40a8a5734
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/thanos-receive-controller-acm-212@sha256:a1882475d1495bd0e859dde171a6abcdc9b4e144b1b2a871b1c768097c08fc62
    name: thanos-receive-controller-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9aff99e56e658c7efa314f4ac7cefec805a1966b
        url: https://github.com/stolostron/thanos-receive-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/kube-rbac-proxy-acm-212@sha256:5fdf31daa502ba8772538e1a9054cd9a90d9936d376db1883db37f1863dc6fb5
    name: kube-rbac-proxy-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: b86d87b4e791731307a5cd838404b0314d2cd06d
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/metrics-collector-acm-212@sha256:3abcff05f72f6be475126946af1fdbe63d9b787574600c35f1381c509ae1b217
    name: metrics-collector-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: collectors/metrics/Containerfile.operator
        revision: 6f12d6be872e2c052926db05eb1ebe304c5a1d78
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/prometheus-config-reloader-acm-212@sha256:022425ddb4a6734c0af407b22e14dacd15228a01bedd296875cb65f3782f3d0d
    name: prometheus-config-reloader-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: cmd/prometheus-config-reloader/Containerfile.operator
        revision: 233733b1cb030fdd82da736940e9e6a1e1bf5d91
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/prometheus-acm-212@sha256:28378ef06db2caf6cc442a060fb554cf7ebfbde14c295f395d61fd70f75cdd30
    name: prometheus-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: e138be46bcece915af3bc44f2b6bae4d9840af71
        url: https://github.com/stolostron/prometheus
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/config-policy-controller-acm-212@sha256:0117f1c014b8e6907bf5b1073119da523a2ab6b4f0b1071721c150c315cfa310
    name: config-policy-controller-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 9db33f7f91b7eece67d0339173c1d5fd1e23a2a7
        url: https://github.com/stolostron/config-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/governance-policy-framework-addon-acm-212@sha256:b1599deb0110cbc6fa2ecb732495573ee6dd7d9b32e72836fd19e197551b6df7
    name: governance-policy-framework-addon-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: c5891ab0ac1aff5641523b9643aa1c91007769f3
        url: https://github.com/stolostron/governance-policy-framework-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/grafana-dashboard-loader-acm-212@sha256:b7e994181de4eb5320e3cf5a019e56be17b267a9d2b005f60caf6d18e90d26ad
    name: grafana-dashboard-loader-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: loaders/dashboards/Containerfile.operator
        revision: 6f12d6be872e2c052926db05eb1ebe304c5a1d78
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-acm-212/multiclusterhub-operator-acm-212@sha256:d79d3b5edb6658ae4e3b030ca8f9001d70852babf211ac32a88e567d3cecc4af
    name: multiclusterhub-operator-acm-212
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: d3f1dd6df91e4de4371c2cfc16ee1406e007b466
        url: https://github.com/stolostron/multiclusterhub-operator
status:
  conditions:
  - lastTransitionTime: "2024-09-18T18:46:24Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2024-09-18T18:46:24Z"
    message: No required IntegrationTestScenarios found, skipped testing
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2024-09-18T18:46:24Z"
    message: Skipping auto-release of the Snapshot because no ReleasePlans have the
      'auto-release' label set to 'true'
    reason: AutoReleased
    status: "True"
    type: AutoReleased
