apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-backup-operator?rev=2a9e100704fe154e17907ae0abb5310ea0069501
    build.appstudio.redhat.com/commit_sha: 2a9e100704fe154e17907ae0abb5310ea0069501
    build.appstudio.redhat.com/target_branch: release-2.16
    pac.test.appstudio.openshift.io/branch: release-2.16
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54984136732"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-vpjhjo
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-backup-operator-acm-216-on-push-x9zgb
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.16"
    pac.test.appstudio.openshift.io/original-prname: cluster-backup-operator-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "1442"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-backup-operator
    pac.test.appstudio.openshift.io/repository: cluster-backup-operator-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 2a9e100704fe154e17907ae0abb5310ea0069501
    pac.test.appstudio.openshift.io/sha-title: 'fix(deps): update module sigs.k8s.io/controller-runtime
      to v0.22.4 (#1442)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-backup-operator/commit/2a9e100704fe154e17907ae0abb5310ea0069501
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.16
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-backup-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-backup-operator
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'acm-cli-acm-216,
      cluster-permission-acm-216, kube-rbac-proxy-acm-216, prometheus-alertmanager-acm-216,
      submariner-addon-acm-216, governance-policy-addon-controller-acm-216, grafana-acm-216,
      multicluster-observability-operator-acm-216, observatorium-acm-216, multicluster-operators-channel-acm-216,
      multicluster-operators-subscription-acm-216, thanos-receive-controller-acm-216,
      cert-policy-controller-acm-216, must-gather-acm-216, prometheus-acm-216, governance-policy-framework-addon-acm-216,
      governance-policy-propagator-acm-216, kube-state-metrics-acm-216, memcached-exporter-acm-216,
      multicluster-observability-addon-acm-216, multicluster-operators-application-acm-216,
      observatorium-operator-acm-216, thanos-acm-216, config-policy-controller-acm-216,
      endpoint-monitoring-operator-acm-216, metrics-collector-acm-216, multicloud-integrations-acm-216,
      prometheus-config-reloader-acm-216, rbac-query-proxy-acm-216, grafana-dashboard-loader-acm-216,
      multicluster-role-assignment-acm-216, node-exporter-acm-216, prometheus-operator-acm-216'
      is(are) not included in snapshot due to missing valid containerImage or git
      source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-216-release-acm-216-jvmmf":{"lastUpdateTime":"2025-11-10T15:21:34.351303568Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762785866"
    test.appstudio.openshift.io/pr-group: refs/heads/release-2.16
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-backup-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-216","status":"TestPassed","lastUpdateTime":"2025-11-10T15:21:34.351303568Z","details":"Integration
      test passed","startTime":"2025-11-10T15:20:48.13924099Z","completionTime":"2025-11-10T15:21:34.351303568Z","testPipelineRunName":"enterprise-contract-acm-216-d5mvd"}]'
  creationTimestamp: "2025-11-10T15:05:51Z"
  generateName: release-acm-216-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-216
    appstudio.openshift.io/build-pipelinerun: cluster-backup-operator-acm-216-on-push-x9zgb
    appstudio.openshift.io/component: cluster-backup-operator-acm-216
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54984136732"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-backup-operator-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "1442"
    pac.test.appstudio.openshift.io/repository: cluster-backup-operator-acm-210
    pac.test.appstudio.openshift.io/sha: 2a9e100704fe154e17907ae0abb5310ea0069501
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-backup-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762787145"
    test.appstudio.openshift.io/pr-group-sha: 3541f3343890e1de964805d2179832e232906962277c9e4d68dd003c503ed1
    test.appstudio.openshift.io/type: component
  name: release-acm-216-jvmmf
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-216
    uid: 36e17c1d-3fe4-44ec-96e0-7fac572eda72
  resourceVersion: "5780978929"
  uid: b5a0c8dd-b75d-411c-b2ba-c17d46a80360
spec:
  application: release-acm-216
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-216@sha256:506aa32aa43b96f6eb83003228d5facd82a2bb69e013800a39af6611b326a99f
    name: klusterlet-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 31d78023b7f23d35f82eef5f0cb8c58a9e32cc2c
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-216@sha256:7909a5eb9194bb4c5c5f8b2a97852174e097f10e17d5455ca516695ec3d68616
    name: search-collector-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 95972870f9caa2b81b49558c7d8ec523b5e4703b
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-216@sha256:bccb3c83522a7ea9903bc99cab316b2f83707eff540d4dafcc02e971d0acaed0
    name: volsync-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4298b79e1fe3b7f2df4e731c169cd6979996481f
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-216@sha256:74e14840ec89a871ee1f473463104f3aabc82149c347fef0fe741e38d0fefe3c
    name: cluster-backup-operator-acm-216
    source:
      git:
        revision: 2a9e100704fe154e17907ae0abb5310ea0069501
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-216@sha256:43fd351fa21c3739886696cb50cbe0ef5ae9435be8aacd7d44438393181506ae
    name: multiclusterhub-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 121a65bd60492e83448a6b8590676852c2792a7e
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-216@sha256:6c726950d3d380cc46e926cc5338d6fc2d9e9cb1789da75b44e2a32ebbd909e0
    name: search-v2-api-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1df5634cc09a3eb7257b5f5d02c5ad01d3b3d295
        url: https://github.com/stolostron/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-216@sha256:b0bca20324584e8b9fd4c6bbebb972f46e8ed8caf99850d91469ae3b09c789f0
    name: siteconfig-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 5c7948458a83dd750efc7c73eb995dc2d16d1a6f
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-216@sha256:2b6f1e57833aa98d7e0acec558b1da44138b1eed22185bb4459d41463f1cb193
    name: insights-client-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c5a46b852fdcf8d875379289637fa1d93fabb844
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-216@sha256:3f8b4784bcdd6a05757c94a8a5b402e441cfda04b9613bcf4ff2482a0f851a83
    name: mtv-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: c7bfbe48b4e0de377b69c6fefdfd5a40f4615c23
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-216@sha256:277e2546dd5523114a060625447aba92c52c5906c77699a7f8f14b23465e51f9
    name: search-v2-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c67352e80db2c462de883f0484a3c8d550fdbb90
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-216@sha256:5019d3c0a8b6681b3859e35ae0f90d1bbfc296f6f65aab0da697d3016a345d24
    name: console-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 71bb5d09f9816a24941ce599370e0b6762c10bc3
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-216@sha256:36f536aeb1506b2149651dd68ed06846a8fdecfa1f5c8440ba887fa0ec192642
    name: insights-metrics-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3260e625b844d64fde64747d65a596d3c9d9cd57
        url: https://github.com/stolostron/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-216@sha256:9c173e37b35b1a9179ac605c8286225d19843d7a93c6b8e29a13835f7b721f8a
    name: search-indexer-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1a8948b97bd3ba4517dcb280122aa5de8ec54693
        url: https://github.com/stolostron/search-indexer
status:
  conditions:
  - lastTransitionTime: "2025-11-10T15:20:47Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-11-10T15:22:29Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-10T15:22:29Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-10T15:22:29Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
