apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-permission?rev=25f12b79a1fd44c502e1e9757ba4d82994be6518
    build.appstudio.redhat.com/commit_sha: 25f12b79a1fd44c502e1e9757ba4d82994be6518
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "62721363276"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-gbsigz
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-permission-acm-217-on-push-kdssf
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "main"
    pac.test.appstudio.openshift.io/original-prname: cluster-permission-acm-217-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-permission
    pac.test.appstudio.openshift.io/repository: cluster-permission-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 25f12b79a1fd44c502e1e9757ba4d82994be6518
    pac.test.appstudio.openshift.io/sha-title: |-
      :seedling: [main] update konflux files (#196)

      * Formatting all tekton files

      Signed-off-by: zhujian <jiazhu@redhat.com>

      * Update konflux CEL from release-2.17 to main

      Signed-off-by: zhujian <jiazhu@redhat.com>

      * Migrate to use common pipeline

      Signed-off-by: zhujian <jiazhu@redhat.com>

      * Update build-platforms to support multi-arch

      Signed-off-by: zhujian <jiazhu@redhat.com>

      * Add slack notification params for push pipelines

      Signed-off-by: zhujian <jiazhu@redhat.com>

      * Add prefetch-input param to all pipelines

      Signed-off-by: zhujian <jiazhu@redhat.com>

      ---------

      Signed-off-by: zhujian <jiazhu@redhat.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-permission/commit/25f12b79a1fd44c502e1e9757ba4d82994be6518
    pac.test.appstudio.openshift.io/source-branch: refs/heads/main
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-permission
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-permission
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-06T07:50:49Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'observatorium-acm-217,
      governance-policy-propagator-acm-217, insights-client-acm-217, multicluster-observability-operator-acm-217,
      multiclusterhub-operator-acm-217, prometheus-alertmanager-acm-217, search-collector-acm-217,
      search-v2-operator-acm-217, cluster-backup-operator-acm-217, endpoint-monitoring-operator-acm-217,
      grafana-dashboard-loader-acm-217, multicluster-operators-application-acm-217,
      multicluster-role-assignment-acm-217, governance-policy-addon-controller-acm-217,
      insights-metrics-acm-217, search-v2-api-acm-217, config-policy-controller-acm-217,
      must-gather-acm-217, prometheus-config-reloader-acm-217, thanos-receive-controller-acm-217,
      thanos-acm-217, governance-policy-framework-addon-acm-217, kube-state-metrics-acm-217,
      memcached-exporter-acm-217, siteconfig-acm-217, acm-cli-acm-217, cert-policy-controller-acm-217,
      kube-rbac-proxy-acm-217, multicluster-operators-subscription-acm-217, prometheus-acm-217,
      submariner-addon-acm-217, obo-prometheus-operator-acm-217, grafana-acm-217,
      multicluster-observability-addon-acm-217, node-exporter-acm-217, prometheus-operator-acm-217,
      rbac-query-proxy-acm-217, search-indexer-acm-217, console-acm-217, metrics-collector-acm-217,
      mtv-integrations-acm-217, multicloud-integrations-acm-217, multicluster-operators-channel-acm-217,
      observatorium-operator-acm-217' is(are) not included in snapshot due to missing
      valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-217-release-acm-217-20260206-073936-000":{"lastUpdateTime":"2026-02-06T07:51:20.849464881Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1770363576000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-permission
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-217","status":"TestPassed","lastUpdateTime":"2026-02-06T07:51:20.849464881Z","details":"Integration
      test passed","startTime":"2026-02-06T07:50:49.386029116Z","completionTime":"2026-02-06T07:51:20.849464881Z","testPipelineRunName":"enterprise-contract-acm-217-t2zbj"}]'
  creationTimestamp: "2026-02-06T07:50:49Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-217
    appstudio.openshift.io/build-pipelinerun: cluster-permission-acm-217-on-push-kdssf
    appstudio.openshift.io/component: cluster-permission-acm-217
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "62721363276"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-permission-acm-217-on-push
    pac.test.appstudio.openshift.io/repository: cluster-permission-acm-210
    pac.test.appstudio.openshift.io/sha: 25f12b79a1fd44c502e1e9757ba4d82994be6518
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-permission
    test.appstudio.openshift.io/pipelinerunfinishtime: "1770364244"
    test.appstudio.openshift.io/type: component
  name: release-acm-217-20260206-073936-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-217
    uid: f6a47cb4-5edb-49df-b280-ca2ad71f1d6c
  resourceVersion: "7111654817"
  uid: c0404df9-9665-4e7c-9816-b3c65e6f6e19
spec:
  application: release-acm-217
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-217@sha256:ed8efad6f05f4d5a5c255eaa9d27fb82afa78f4a43a35bda98c0dfffba7ddd2c
    name: volsync-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fe47f800eb2695f871dfa12d631c93b27820cbed
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-permission-acm-217@sha256:ff7e85e5323ac74eedf0c71c584a76641e055d5430fcd9c72fe3129b92cf204d
    name: cluster-permission-acm-217
    source:
      git:
        revision: 25f12b79a1fd44c502e1e9757ba4d82994be6518
        url: https://github.com/stolostron/cluster-permission
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-217@sha256:335900bab1a31f35bc3f83318ef0f52b1bfed4e8ae03a45792b99e441efcd450
    name: klusterlet-addon-controller-acm-217
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 351170246988c898578145f9823f5bed981d5823
        url: https://github.com/stolostron/klusterlet-addon-controller
status:
  conditions:
  - lastTransitionTime: "2026-02-06T07:51:20Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-06T07:51:20Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-06T07:51:20Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
