apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicloud-integrations?rev=f72bc9a183f810de77e69e49edb434defab7a933
    build.appstudio.redhat.com/commit_sha: f72bc9a183f810de77e69e49edb434defab7a933
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "96568612497"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-bsdvir
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/multicloud-integrations-acm-52-on-push-dp49t
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "main"
    pac.test.appstudio.openshift.io/original-prname: multicloud-integrations-acm-52-on-push
    pac.test.appstudio.openshift.io/pull-request: "604"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicloud-integrations
    pac.test.appstudio.openshift.io/repository: multicloud-integrations-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: xiangjingli
    pac.test.appstudio.openshift.io/sha: f72bc9a183f810de77e69e49edb434defab7a933
    pac.test.appstudio.openshift.io/sha-title: |-
      Add Tekton files for versions: 5.1 5.2 (#604)

      Signed-off-by: OpenShift CI Robot <noreply@openshift.io>
      Co-authored-by: OpenShift CI Robot <noreply@openshift.io>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicloud-integrations/commit/f72bc9a183f810de77e69e49edb434defab7a933
    pac.test.appstudio.openshift.io/source-branch: refs/heads/main
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-integrations
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-integrations
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-08-20T20:28:46Z"}'
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'acm-cli-acm-52,
      insights-client-acm-52, grafana-acm-52, cert-policy-controller-acm-52, multicluster-operators-subscription-acm-52,
      observatorium-operator-acm-52, must-gather-acm-52, cluster-backup-operator-acm-52,
      dynamic-scoring-controller-acm-52, thanos-receive-controller-acm-52, console-acm-52,
      search-v2-operator-acm-52, kube-rbac-proxy-acm-52, cluster-permission-acm-52,
      search-v2-api-acm-52, observatorium-acm-52, node-exporter-acm-52, search-indexer-acm-52,
      klusterlet-addon-controller-acm-52, grafana-dashboard-loader-acm-52, search-collector-acm-52,
      governance-policy-propagator-acm-52, multicluster-role-assignment-acm-52, prometheus-acm-52,
      config-policy-controller-acm-52, mtv-integrations-acm-52, insights-metrics-acm-52,
      prometheus-config-reloader-acm-52, endpoint-monitoring-operator-acm-52, volsync-addon-controller-acm-52,
      submariner-addon-acm-52, governance-policy-framework-addon-acm-52, metrics-collector-acm-52,
      thanos-acm-52, multiclusterhub-operator-acm-52, memcached-exporter-acm-52, siteconfig-acm-52,
      multicluster-observability-addon-acm-52, prometheus-alertmanager-acm-52, kube-state-metrics-acm-52,
      multicluster-observability-operator-acm-52, governance-policy-addon-controller-acm-52,
      dynamic-scoring-addon-acm-52, prometheus-operator-acm-52, obo-prometheus-operator-acm-52,
      rbac-query-proxy-acm-52' is(are) not included in snapshot due to missing valid
      containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-52-release-acm-52-20260820-201753-000":{"lastUpdateTime":"2026-08-20T20:29:31.154848061Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1787257073000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/result-chains-git-commit: f72bc9a183f810de77e69e49edb434defab7a933
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/stolostron/multicloud-integrations
    test.appstudio.openshift.io/result-image-digest: sha256:03b3cf106eefccebcbe78ff26d44a1478d65e66fbcdc3076c1eb1ac13c7bb7d1
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-52:f72bc9a183f810de77e69e49edb434defab7a933
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-integrations
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-52","status":"BuildPLRInProgress","lastUpdateTime":"2026-08-20T20:29:31.154848061Z","details":"Integration
      test passed with warnings","startTime":"2026-08-20T20:28:46.630389109Z","completionTime":"2026-08-20T20:29:31.154848061Z","testPipelineRunName":"enterprise-contract-acm-52-8n78g"}]'
  creationTimestamp: "2026-08-20T20:28:46Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-52
    appstudio.openshift.io/build-pipelinerun: multicloud-integrations-acm-52-on-push-dp49t
    appstudio.openshift.io/component: multicloud-integrations-acm-52
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "96568612497"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multicloud-integrations-acm-52-on-push
    pac.test.appstudio.openshift.io/pull-request: "604"
    pac.test.appstudio.openshift.io/repository: multicloud-integrations-acm-210
    pac.test.appstudio.openshift.io/sha: f72bc9a183f810de77e69e49edb434defab7a933
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-integrations
    test.appstudio.openshift.io/pipelinerunfinishtime: "1787257720"
    test.appstudio.openshift.io/type: component
  name: release-acm-52-20260820-201753-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-52
    uid: cfc033ef-9dfc-426e-9763-dbb135f75288
  resourceVersion: "10697626391"
  uid: 58ff757d-a159-4d29-980e-a18cd872783c
spec:
  application: release-acm-52
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-application-acm-52@sha256:aaf985607717420e00806ccf806c4a5dd665d678fc3239278e5ae800388d4c7a
    name: multicluster-operators-application-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: bbb0fa1ac86c57266fa7f8729be35096810ba42f
        url: https://github.com/stolostron/multicloud-operators-application
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-integrations-acm-52@sha256:03b3cf106eefccebcbe78ff26d44a1478d65e66fbcdc3076c1eb1ac13c7bb7d1
    name: multicloud-integrations-acm-52
    source:
      git:
        context: ./
        revision: f72bc9a183f810de77e69e49edb434defab7a933
        url: https://github.com/stolostron/multicloud-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-operators-channel-acm-52@sha256:166fe5ddf7241b14ddceaf068fb0fcc6f801f994b7a1e438d8291b476e3f0f85
    name: multicluster-operators-channel-acm-52
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2c60c48067a73e124ebef9dfb9a829d322d14d32
        url: https://github.com/stolostron/multicloud-operators-channel
status:
  conditions:
  - lastTransitionTime: "2026-08-20T20:29:31Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-08-20T20:29:31Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-08-20T20:29:31Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
