apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multiclusterhub-operator?rev=defb69aca02b5d168b91f98aebda355b7446ff1f
    build.appstudio.redhat.com/commit_sha: defb69aca02b5d168b91f98aebda355b7446ff1f
    build.appstudio.redhat.com/target_branch: release-2.16
    pac.test.appstudio.openshift.io/branch: release-2.16
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54739331708"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-oxsynp
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/multiclusterhub-operator-acm-216-on-push-l6jx9
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-2.16"
    pac.test.appstudio.openshift.io/original-prname: multiclusterhub-operator-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "2858"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multiclusterhub-operator
    pac.test.appstudio.openshift.io/repository: multiclusterhub-operator-acm-210
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: defb69aca02b5d168b91f98aebda355b7446ff1f
    pac.test.appstudio.openshift.io/sha-title: Red Hat Konflux update multiclusterhub-operator-acm-216
      (#2858)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multiclusterhub-operator/commit/defb69aca02b5d168b91f98aebda355b7446ff1f
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-2.16
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multiclusterhub-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multiclusterhub-operator
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'multicluster-observability-addon-acm-216,
      multicluster-observability-operator-acm-216, multicluster-operators-application-acm-216,
      acm-cli-acm-216, cert-policy-controller-acm-216, governance-policy-propagator-acm-216,
      multicluster-operators-subscription-acm-216, prometheus-config-reloader-acm-216,
      search-collector-acm-216, thanos-receive-controller-acm-216, governance-policy-addon-controller-acm-216,
      grafana-acm-216, search-v2-api-acm-216, search-v2-operator-acm-216, search-indexer-acm-216,
      submariner-addon-acm-216, cluster-permission-acm-216, governance-policy-framework-addon-acm-216,
      memcached-exporter-acm-216, prometheus-operator-acm-216, thanos-acm-216, grafana-dashboard-loader-acm-216,
      kube-rbac-proxy-acm-216, observatorium-operator-acm-216, prometheus-acm-216,
      insights-client-acm-216, config-policy-controller-acm-216, endpoint-monitoring-operator-acm-216,
      metrics-collector-acm-216, node-exporter-acm-216, multicluster-role-assignment-acm-216,
      prometheus-alertmanager-acm-216, rbac-query-proxy-acm-216, kube-state-metrics-acm-216,
      observatorium-acm-216, multicluster-operators-channel-acm-216, must-gather-acm-216,
      insights-metrics-acm-216, multicloud-integrations-acm-216' is(are) not included
      in snapshot due to missing valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-acm-216-release-acm-216-kdpvb":{"lastUpdateTime":"2025-11-06T21:46:05.642498546Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762464828"
    test.appstudio.openshift.io/pr-group: refs/heads/release-2.16
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multiclusterhub-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-acm-216","status":"TestPassed","lastUpdateTime":"2025-11-06T21:46:05.642498546Z","details":"Integration
      test passed","startTime":"2025-11-06T21:45:32.703037302Z","completionTime":"2025-11-06T21:46:05.642498546Z","testPipelineRunName":"enterprise-contract-acm-216-6c889"}]'
  creationTimestamp: "2025-11-06T21:45:32Z"
  generateName: release-acm-216-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-216
    appstudio.openshift.io/build-pipelinerun: multiclusterhub-operator-acm-216-on-push-l6jx9
    appstudio.openshift.io/component: multiclusterhub-operator-acm-216
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54739331708"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multiclusterhub-operator-acm-216-on-push
    pac.test.appstudio.openshift.io/pull-request: "2858"
    pac.test.appstudio.openshift.io/repository: multiclusterhub-operator-acm-210
    pac.test.appstudio.openshift.io/sha: defb69aca02b5d168b91f98aebda355b7446ff1f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multiclusterhub-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762465526"
    test.appstudio.openshift.io/pr-group-sha: 3541f3343890e1de964805d2179832e232906962277c9e4d68dd003c503ed1
    test.appstudio.openshift.io/type: component
  name: release-acm-216-kdpvb
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-216
    uid: 36e17c1d-3fe4-44ec-96e0-7fac572eda72
  resourceVersion: "5739231922"
  uid: 8c833eec-a2a7-4444-955e-a8bbfddf1c36
spec:
  application: release-acm-216
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-216@sha256:d2e7dae21984d66e6f4ad4c4380a64293e69bbeb9cbe099b465de9861e95ebc7
    name: klusterlet-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0e723e55e1cc08c5760be7d66f4db1910c73b08b
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-216@sha256:e6315f0dd3f8f1afbb5c7b0bd236509c7a099b4a4be3aa6dfe8f2de209089eef
    name: console-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 1a5630ba79cbe787cd2dbf01efc0e0c571c14e05
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-216@sha256:50813fcaeb2aa9615408043b00dbc75d3b6e108d2769e9656ab91bcbe53a9017
    name: volsync-addon-controller-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 06935af5b3bbf55ec6a847d95175040ed1778561
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-216@sha256:c23d87fd421c7389d2509a2257c6bebed4cc6eb051b1bbc8642dc9954bb37dd7
    name: cluster-backup-operator-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e26adc44012ec614ca8c5b97e157435c47294b24
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mtv-integrations-acm-216@sha256:3f8b4784bcdd6a05757c94a8a5b402e441cfda04b9613bcf4ff2482a0f851a83
    name: mtv-integrations-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: c7bfbe48b4e0de377b69c6fefdfd5a40f4615c23
        url: https://github.com/stolostron/mtv-integrations
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-216@sha256:f256d41485714938211c7759323210aa59d78e61a3f65c29a1d160f6d4bfdca5
    name: multiclusterhub-operator-acm-216
    source:
      git:
        revision: defb69aca02b5d168b91f98aebda355b7446ff1f
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-216@sha256:32d16c2e6bdc7cd146c5d492c703ce215129f25b0b2c7aee5dd74c0f7aeb2ab3
    name: siteconfig-acm-216
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 605fc9ef0b609efada7ae676e4142ae6d507086d
        url: https://github.com/stolostron/siteconfig
status:
  conditions:
  - lastTransitionTime: "2025-11-06T21:45:32Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-11-06T21:46:05Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-06T21:46:05Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-06T21:46:05Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
