apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicluster-observability-operator?rev=98caa2377836dd1a7338941cce5b623c7ad16c2f
    build.appstudio.redhat.com/commit_sha: 98caa2377836dd1a7338941cce5b623c7ad16c2f
    build.appstudio.redhat.com/pull_request_number: "1928"
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/check-run-id: "39708360639"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: retest-all-comment
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-zgxkbm
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://console.redhat.com/application-pipeline/ns/crt-redhat-acm-tenant/pipelinerun/endpoint-monitoring-operator-acm-214-on-pull-request-fj4v5
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "pull_request" &&
      target_branch == "main"
    pac.test.appstudio.openshift.io/original-prname: endpoint-monitoring-operator-acm-214-on-pull-request
    pac.test.appstudio.openshift.io/pull-request: "1928"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicluster-observability-operator
    pac.test.appstudio.openshift.io/repository: endpoint-monitoring-operator-acm-210
    pac.test.appstudio.openshift.io/sender: jacobbaungard
    pac.test.appstudio.openshift.io/sha: 98caa2377836dd1a7338941cce5b623c7ad16c2f
    pac.test.appstudio.openshift.io/sha-title: go mod tidy
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicluster-observability-operator/commit/98caa2377836dd1a7338941cce5b623c7ad16c2f
    pac.test.appstudio.openshift.io/source-branch: upgrade-x-xrypto
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/thibaultmg/multicluster-observability-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicluster-observability-operator
    test.appstudio.openshift.io/create-groupsnapshot-status: build PLR rbac-query-proxy-acm-214-on-pull-request-d9kg5
      failed for component rbac-query-proxy-acm-214 so it can't be added to the group
      Snapshot for PR group upgrade-x-xrypto
    test.appstudio.openshift.io/pipelinerunstarttime: "1743434629"
    test.appstudio.openshift.io/pr-group: upgrade-x-xrypto
    test.appstudio.openshift.io/source-repo-url: https://github.com/thibaultmg/multicluster-observability-operator
  creationTimestamp: "2025-03-31T16:06:25Z"
  generateName: release-acm-214-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-acm-214
    appstudio.openshift.io/build-pipelinerun: endpoint-monitoring-operator-acm-214-on-pull-request-fj4v5
    appstudio.openshift.io/component: endpoint-monitoring-operator-acm-214
    pac.test.appstudio.openshift.io/check-run-id: "39708360639"
    pac.test.appstudio.openshift.io/event-type: retest-all-comment
    pac.test.appstudio.openshift.io/original-prname: endpoint-monitoring-operator-acm-214-on-pull-request
    pac.test.appstudio.openshift.io/pull-request: "1928"
    pac.test.appstudio.openshift.io/repository: endpoint-monitoring-operator-acm-210
    pac.test.appstudio.openshift.io/sha: 98caa2377836dd1a7338941cce5b623c7ad16c2f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicluster-observability-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1743437159"
    test.appstudio.openshift.io/pr-group-sha: aa45ec56056c6183f7150036035b2cde263a0fa769dfdc8c7d608f37236070
    test.appstudio.openshift.io/type: component
  name: release-acm-214-9c4pq
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-acm-214
    uid: 04c282c2-01dd-419b-9cbb-81e1906b94c1
  resourceVersion: "3507032434"
  uid: cd94f099-8806-4c9e-b3f6-69198d5eebe3
spec:
  application: release-acm-214
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-framework-addon-acm-214@sha256:f464c26f895c5fa8ca18b42e85bf64b1bcde9d483de926171107c223645f49ca
    name: governance-policy-framework-addon-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: df391d7e89f6356fa4649ddea8b67bb0ece38ddc
        url: https://github.com/stolostron/governance-policy-framework-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-state-metrics-acm-214@sha256:06c2e833243927035631acc86bb18bb763d4761fa6d76f737ccad00c2b69adbc
    name: kube-state-metrics-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 16d5b8cdbc5e809a5076e39d6149fb10adc714bc
        url: https://github.com/stolostron/kube-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/metrics-collector-acm-214@sha256:bc0ce2e800a81b05704801576884d37cb80bba7a78a1f57c4dd1593155f73c81
    name: metrics-collector-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: collectors/metrics/Containerfile.operator
        revision: 00cca27614da198b53560379ff2c3999c4e9f1ae
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/must-gather-acm-214@sha256:25de733add24941875bc172bdb53b2a4fa478efab235dcaf2d6ea67298e0d289
    name: must-gather-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 6aadf96e2c31d963e132c4ea92112cab2a737eb6
        url: https://github.com/stolostron/must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/node-exporter-acm-214@sha256:a261f0cde4c2d7bb4b30d79fee6dddd79af84ce556c2e9e256b8af096c2401b8
    name: node-exporter-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: ca3b7796e1711922afe68c67cbc8e41e1883d3eb
        url: https://github.com/stolostron/node-exporter
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-acm-214@sha256:461aba141cafce53abd23577d11266f670693704200c6c1784a3a8502895358a
    name: siteconfig-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: c99828c6b2eb1d2c254a8481f47ed455a292f988
        url: https://github.com/stolostron/siteconfig
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cert-policy-controller-acm-214@sha256:285e1f88cffcb60240190eb810709d61a506b3661e71a15a69736ae78756749c
    name: cert-policy-controller-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 12160dbdf75807ece47c918ec17abb2e4febf09d
        url: https://github.com/stolostron/cert-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller-acm-214@sha256:3358a7f31764eacf3be193ac8871af5aac58af7dc20a8170b3edf0d3de26e92c
    name: config-policy-controller-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 74f650f1fa41b9c08104951674ebb48969b86e7c
        url: https://github.com/stolostron/config-policy-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/endpoint-monitoring-operator-acm-214@sha256:df81e5c95fe50c9419c09dfad9ed3d71578b937975389a2031e8cc2d55671271
    name: endpoint-monitoring-operator-acm-214
    source:
      git:
        revision: 98caa2377836dd1a7338941cce5b623c7ad16c2f
        url: https://github.com/thibaultmg/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-operator-acm-214@sha256:173e4d34d0dbc5bd447c1148db20d1750473b46c8a74bcc8b9f0b7923c87e30f
    name: observatorium-operator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 30cf40fd406c952572c305d8f7b9fb8fd25a80bd
        url: https://github.com/stolostron/observatorium-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/acm-cli-acm-214@sha256:5e31d9242edf043c5851206f832ea0c3a7e6c9f4baa72d41aff5b92366fbb086
    name: acm-cli-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d6bc2209441a038735a5609d47943141c1ecc7af
        url: https://github.com/stolostron/acm-cli
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-propagator-acm-214@sha256:7db659136a18d7d791c77ae3d5af7c4e7dbef6723cc7b0db20ae0fa5243bc5da
    name: governance-policy-propagator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1200df3aafd8027d49ab1bf6a5aab1d909fc7de9
        url: https://github.com/stolostron/governance-policy-propagator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-client-acm-214@sha256:406b0ce21be7de56d71013270a577c50e74a0472298ceab482054d6ba5b09fc1
    name: insights-client-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0c0d1d948648be2b72090120c8897f70dd67f98f
        url: https://github.com/stolostron/insights-client
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/klusterlet-addon-controller-acm-214@sha256:9299c799c58852965a5a10960244cd50c56faa92da26673638f7f9c86a431ba3
    name: klusterlet-addon-controller-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fed1b53d9d13d7a78f09f72aa1fe75118b344caa
        url: https://github.com/stolostron/klusterlet-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multiclusterhub-operator-acm-214@sha256:4440c6084f33f69f0db378a67927e1b759cc1f8bb84ee0fd30973b58fa6fe506
    name: multiclusterhub-operator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1e14868a8faf2eb315f4a6fcfb638e019e16d97b
        url: https://github.com/stolostron/multiclusterhub-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-collector-acm-214@sha256:b37f9a9ea1f93bcd66d50906c2343d7de279b91a8355d8292de0da44c40e9121
    name: search-collector-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 99bc7617269438741e3ee56bcc09e22a3affe03e
        url: https://github.com/stolostron/search-collector
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-api-acm-214@sha256:d05c8d53c09f18e542b6be9f9d781f9d2e1f4c0f48655f5582d93da2c712777a
    name: search-v2-api-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5c63067c815d84320a4ea107cb952a4bf6e50fb1
        url: https://github.com/stolostron/search-v2-api
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/thanos-acm-214@sha256:1c78c37f2216b8299a67ce1107b66be1b4096dc7bbaced74fc4b6f4581634b2a
    name: thanos-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: c847ac2943278a2beef98861a7fb3906675634da
        url: https://github.com/stolostron/thanos
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/grafana-acm-214@sha256:02aebbc20463780ac476ebff7f032a62b5cbd180ea72cec94e6e7dcaccbd6dc5
    name: grafana-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: b265c013bea6a3b964a50060b674a6cfaf03079b
        url: https://github.com/stolostron/grafana
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/grafana-dashboard-loader-acm-214@sha256:8115a318fb44e050e22cbc76af1c6351c853896f818b53404d9cfe4d3ea54e81
    name: grafana-dashboard-loader-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: loaders/dashboards/Containerfile.operator
        revision: 00cca27614da198b53560379ff2c3999c4e9f1ae
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/insights-metrics-acm-214@sha256:2a1b9695ef8f8bb8fa34c8d95945026290f8b70ebcab139e862c89ea3cc1008b
    name: insights-metrics-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6bdc8035d6aab2874c4d18ce28c2a2b2130ac362
        url: https://github.com/stolostron/insights-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/observatorium-acm-214@sha256:6137901ce289a546e7836a816a797dc182007296e83424d17671c36572fff403
    name: observatorium-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 64f825470155338c7bdcaa565ee9f1af2eae0bd6
        url: https://github.com/stolostron/observatorium
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-alertmanager-acm-214@sha256:a8d43927d84601ed188f62be1840206bfb6fea0a14ac239a5cc97fd7725bd0ea
    name: prometheus-alertmanager-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 40222698d434cc9177b63485aca8e5b056c65f11
        url: https://github.com/stolostron/prometheus-alertmanager
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/rbac-query-proxy-acm-214@sha256:546b3179f8fdeb2702f481ddc35b9e530a69d2d661364541963128124206b9e0
    name: rbac-query-proxy-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: proxy/Containerfile.operator
        revision: 00cca27614da198b53560379ff2c3999c4e9f1ae
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/volsync-addon-controller-acm-214@sha256:ff1b9325331bcb46c7a5898b92b090abb13c10899eb5d01ed85485735992cf45
    name: volsync-addon-controller-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 69061564c492da50f57a438e10302c5c6cdc07a3
        url: https://github.com/stolostron/volsync-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-observability-operator-acm-214@sha256:1be505c6f04244e3a8d9a7b8c26690a71b5020ba31f98f1ebc1b2bb2053c22fb
    name: multicluster-observability-operator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: operators/multiclusterobservability/Containerfile.operator
        revision: 00cca27614da198b53560379ff2c3999c4e9f1ae
        url: https://github.com/stolostron/multicluster-observability-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-operator-acm-214@sha256:ba978c56f8a71c6ff1db375a4e3f76049d001aa8f6053a1480f1a4073c5dc9af
    name: prometheus-operator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 07bf5761781e81a1af1d06f3b79b82974b0f26ac
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-v2-operator-acm-214@sha256:02c467bb425a1b32da12809a57e4fe800304a8530964420fee8e4954f997c7db
    name: search-v2-operator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c789830f4144533e3903db095381f8b171eec8ef
        url: https://github.com/stolostron/search-v2-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/thanos-receive-controller-acm-214@sha256:23d07ff82cf65621bc5211d224095f34d8b771ecad6fa8d02e28efba339fc1d5
    name: thanos-receive-controller-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 10d1d31684a17c23a7405bb6943c8ae0dfce2163
        url: https://github.com/stolostron/thanos-receive-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-acm-214@sha256:3074c0f61a0bb9e7667cbe47f4a1a9a6ff20fa794295ef5c39294521696058e4
    name: console-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.acm.konflux
        revision: 5ff3f28df082d97a971910c86441e71420052e0f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/prometheus-config-reloader-acm-214@sha256:d1c009ff5249a22e54cb06dc560af8224a43d34122737957906acc0289116642
    name: prometheus-config-reloader-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: cmd/prometheus-config-reloader/Containerfile.operator
        revision: 07bf5761781e81a1af1d06f3b79b82974b0f26ac
        url: https://github.com/stolostron/prometheus-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-backup-operator-acm-214@sha256:f5f0aaad15a1a01bcf7137502691a0e890b1327d4c5d85ce94238def001d80ab
    name: cluster-backup-operator-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5c0b1454331ce59cada05267e4cc605f7b74a72a
        url: https://github.com/stolostron/cluster-backup-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/governance-policy-addon-controller-acm-214@sha256:8183969eefcfc1b8b91e3db0131f487bdfbe4fad551f49d70597e86711db16c4
    name: governance-policy-addon-controller-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 2bcf01e8fc6db7d9b5474d57a6bbae1cd7d7ea25
        url: https://github.com/stolostron/governance-policy-addon-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-acm-214@sha256:35adb02919845139eb5d66cfd9e3f173825256fdb8bfaa95a6ef2ac80a09fa4f
    name: kube-rbac-proxy-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 32dfd54b4d2e2f990f31aaf72c5a5df300a8329b
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicluster-observability-addon-acm-214@sha256:45b8f69ff4862f5869d691038eff09fb97bf6387e32d0e30cae80b9f9023d8ea
    name: multicluster-observability-addon-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 782f0e1f93b240d1affa730ceccbb9bc1f492d0a
        url: https://github.com/stolostron/multicluster-observability-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/search-indexer-acm-214@sha256:ee15274a4cb5cdd9f5ab9d2723955bfa95bf4bb710799e258a52ac53061ca0bd
    name: search-indexer-acm-214
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b296a618625330eca38c957c3a540b21ba24533a
        url: https://github.com/stolostron/search-indexer
status:
  conditions:
  - lastTransitionTime: "2025-03-31T16:06:25Z"
    message: No required IntegrationTestScenarios found, skipped testing
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
