apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/acm-operator-bundle?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-2.12"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: bundle-release-acm-212
    appstudio.openshift.io/component: acm-operator-bundle-acm-212
    pipelines.appstudio.openshift.io/type: build
  name: acm-operator-bundle-acm-212-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/acm-operator-bundle-acm-212:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: send-slack-notification
    value: true
  - name: konflux-application-name
    value: release-acm-212
  - name: slack-member-id
    value: S05L3R4SM89 # @acm-hub-install-ic, The slack member id of the current component owner.
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-acm-operator-bundle-acm-212
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}